### ISSUE TITLE
分享崩溃[官方Demo也崩溃]： android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.sina.weibo.bundlemanager.BundleConfigReader$WBBundleComponentConfig

### ISSUE THREAD

**Issue by thduan** [sinaweibosdk/weibo_android_sdk#100]
weiboSDKCore_3.1.2 分享崩溃【官方Demo也崩溃】：

重现步骤：
1. 安装新浪微博客户端【Version5.5.0 Beta（目前的最新版本）】，安装完之后不要启动；如果之前安装过微博客户端，则先卸载后再安装；
2. 启动WeiboSDKDemo【该demo中 APP_KEY已修改为可用的了】；
    依次点击 ：分享到微博 --> 注册应用到微博 --> 分享到微博（ALL IN ONE） --> 勾选“分享文字”、“分享图片” --> 点击“分享”按钮 --> 弹出登录微博账号界面 --> 输入账号信息 --> 点击“登录”
    稍等一会后 客户端崩溃，崩溃日志如下：
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.sina.weibo.bundlemanager.BundleConfigReader$WBBundleComponentConfig
at android.os.Parcel.readParcelable(Parcel.java:2080)
at android.os.Parcel.readValue(Parcel.java:1968)
at android.os.Parcel.readMapInternal(Parcel.java:2229)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getString(Bundle.java:1063)
at android.content.Intent.getStringExtra(Intent.java:4541)
at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.handleWeiboResponse(WeiboShareAPIImpl.java:179)
at com.sina.weibo.sdk.demo.WBShareActivity.onNewIntent(WBShareActivity.java:128)
at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1226)
at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2498)
at android.app.ActivityThread.performNewIntents(ActivityThread.java:2511)
at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2520)
at android.app.ActivityThread.access$1400(ActivityThread.java:171)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1464)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5468)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:934)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)
at dalvik.system.NativeStart.main(Native Method)

希望官方能尽快修复该问题，谢谢！

**Comment by Jungerr** [comment]
我也遇到这情况。

**Comment by thduan** [comment]
我咨询了官方人员，原因是 在分享之前需要获取授权， 没获取到授权就会出现该问题；
他说官方的SDK Demo 后续会更新。
