### ISSUE TITLE
3.1.4版本 getNinePatchDrawable 抛出空异常

### ISSUE THREAD

**Issue by lwangwangl** [sinaweibosdk/weibo_android_sdk#140]
使用的是最新版本的sdk， 3.1.4，
看bug里以前也有人提到过，怀疑是不是自己的工程有什么配置错误，还请指正，
以下是崩溃日志：

r:Xiaomi^M
model:MI 2A^M
exception:java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 4.6.9f1
Device model      : Xiaomi MI 2A
Device fingerprint: Xiaomi/taurus/taurus:4.1.1/JRO03L/4.12.5:user/release-keys
^M
crashMD5:4930ec7d8fd11a1b04bcde2dc55e1519^M
crashDump:{java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 4.6.9f1
Device model      : Xiaomi MI 2A
Device fingerprint: Xiaomi/taurus/taurus:4.1.1/JRO03L/4.12.5:user/release-keys

Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxx/com.sina.weibo.sdk.component.WeiboSdkBrowser}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2092)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
        at android.app.ActivityThread.access$600(ActivityThread.java:140)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4914)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
        at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:328)
        at android.content.res.AssetManager.open(AssetManager.java:302)
        at com.sina.weibo.sdk.utils.ResourceManager.getDrawableFromAssert(ResourceManager.java:209)
        at com.sina.weibo.sdk.utils.ResourceManager.getNinePatchDrawable(ResourceManager.java:114)
        at com.sina.weibo.sdk.component.WeiboSdkBrowser.initTitleBar(WeiboSdkBrowser.java:377)
        at com.sina.weibo.sdk.component.WeiboSdkBrowser.setContentView(WeiboSdkBrowser.java:273)
        at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:131)
        at android.app.Activity.performCreate(Activity.java:5086)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
        at com.lbe.security.service.core.client.b.x.callActivityOnCreate(Unknown Source)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
        ... 11 more
}^M

**Comment by WNervous** [comment]
遇到相同的问题，看了一下源码，   path    可能为空，原因是filename 为空，但是fileName 在哪用就没找到了。。
`
   public static Drawable getNinePatchDrawable(Context context, String fileName) {
        String path = getAppropriatePathOfDrawable(context, fileName);
        return getDrawableFromAssert(context, path, true);
    }


 private static Drawable getDrawableFromAssert(Context context, String relativePath, boolean isNinePatch) {
        Drawable rtDrawable = null;
        AssetManager asseets = context.getAssets();
        InputStream is = null;

        try {
            is = asseets.open(relativePath);
            if (is != null) {
                Bitmap bitmap = BitmapFactory.decodeStream(is);
                DisplayMetrics metrics = context.getResources().getDisplayMetrics();
                if (isNinePatch) {
                    Configuration config = context.getResources().getConfiguration();
                    Resources res = new Resources(context.getAssets(), metrics, config);
                    rtDrawable = new NinePatchDrawable(res, bitmap, bitmap.getNinePatchChunk(), new Rect(0, 0, 0, 0), (String)null);
                } else {
                    bitmap.setDensity(metrics.densityDpi);
                    rtDrawable = new BitmapDrawable(context.getResources(), bitmap);
                }
            }
        } catch (IOException var18) {
            var18.printStackTrace();
        } finally {
            if (is != null) {
                try {
                    is.close();
                } catch (IOException var17) {
                    var17.printStackTrace();
                }

                is = null;
            }

        }

        return (Drawable)rtDrawable;
    }`
