### ISSUE TITLE
Android SDK 3.0.1  --  bug

### ISSUE THREAD

**Issue by tjs4571** [sinaweibosdk/weibo_android_sdk#153]
你好：
    我在使用微博开放平台提供的（Android sdk 3.0.1 ）时遇到了困难
    问题描述：
        我们的 Android 版 App 股票入门基础知识  包名 com.gaotonghuanqiu.stockguide，

```
    线上版的app 由于 weiboSDKCore_3.0.1.jar 中的 WeiboSdkBrowser.java 中报出 NullPointerException 导致我们的 app crash。希望能得到您的协助。。谢谢！

    详细报错信息（针对api和sdk的使用者）：线上的 App 报错信息如下：

   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gaotonghuanqiu.stockguide/com.sina.weibo.sdk.component.WeiboSdkBrowser}: java.lang.NullPointerException   5   2016/3/31 15:30 1.0.3.1 "java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gaotonghuanqiu.stockguide/com.sina.weibo.sdk.component.WeiboSdkBrowser}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
at android.app.ActivityThread.access$800(ActivityThread.java:138)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5024)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
```

Caused by: java.lang.NullPointerException
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.createBrowserRequestParam(Unknown Source)
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.initDataFromIntent(Unknown Source)
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(Unknown Source)
    at android.app.Activity.performCreate(Activity.java:5231)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
    ... 11 more
java.lang.NullPointerException
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.createBrowserRequestParam(Unknown Source)
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.initDataFromIntent(Unknown Source)
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(Unknown Source)
    at android.app.Activity.performCreate(Activity.java:5231)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
    at android.app.ActivityThread.access$800(ActivityThread.java:138)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5024)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)

```
 希望能尽快受到您的回复。
```

**Comment by BriceChou** [comment]
Same as issue #168 .
BR.
