### ISSUE TITLE
有时候会报Empty file name

### ISSUE THREAD

**Issue by qinci** [sinaweibosdk/weibo_android_sdk#155]
Caused by: java.lang.IllegalArgumentException: Empty file name
                                                                             at android.content.res.AssetManager.openAsset(Native Method)
                                                                             at android.content.res.AssetManager.open(AssetManager.java:331)
                                                                             at android.content.res.AssetManager.open(AssetManager.java:305)
                                                                             at com.sina.weibo.sdk.utils.ResourceManager.getDrawableFromAssert(ResourceManager.java:209)
                                                                             at com.sina.weibo.sdk.utils.ResourceManager.getNinePatchDrawable(ResourceManager.java:114)
                                                                             at com.sina.weibo.sdk.component.WeiboSdkBrowser.initTitleBar(WeiboSdkBrowser.java:377)
                                                                             at com.sina.weibo.sdk.component.WeiboSdkBrowser.setContentView(WeiboSdkBrowser.java:273)
                                                                             at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:131)

**Comment by liuyangzzu** [comment]
I encountered the same error.

                                                                        --------- beginning of crash
05-08 17:37:38.516 10224-10224/com.sina.weibo.sdk.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.sina.weibo.sdk.demo, PID: 10224
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sina.weibo.sdk.demo/com.sina.weibo.sdk.component.WeiboSdkBrowser}: java.lang.IllegalArgumentException: Empty file name
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                          Caused by: java.lang.IllegalArgumentException: Empty file name
                                                                             at android.content.res.AssetManager.openAsset(Native Method)
                                                                             at android.content.res.AssetManager.open(AssetManager.java:313)
                                                                             at android.content.res.AssetManager.open(AssetManager.java:287)
                                                                             at com.sina.weibo.sdk.utils.ResourceManager.getDrawableFromAssert(ResourceManager.java:209)
                                                                             at com.sina.weibo.sdk.utils.ResourceManager.getNinePatchDrawable(ResourceManager.java:114)
                                                                             at com.sina.weibo.sdk.component.WeiboSdkBrowser.initTitleBar(WeiboSdkBrowser.java:377)
                                                                             at com.sina.weibo.sdk.component.WeiboSdkBrowser.setContentView(WeiboSdkBrowser.java:273)
                                                                             at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:131)
                                                                             at android.app.Activity.performCreate(Activity.java:5937)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by BriceChou** [comment]
Same as issue #168 .
BR.

**Comment by Joy-Whale** [comment]
同样的问题...

**Comment by e-snail** [comment]
在GIONEE　sdk 23 手机上  复现

**Comment by Muyangmin** [comment]
同样的问题。复现机型信息：
**Huawei FRD-AL00, EMUI 5.0 （Based on Android 7.0, API 24）, 未安装微博客户端。**
