### ISSUE TITLE
小米手机调分享崩溃

### ISSUE THREAD

**Issue by kshw123** [sinaweibosdk/weibo_android_sdk#162]
`Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.sina.weibo.sdk.api.TextObject
                                                                      at android.os.Parcel.readParcelableCreator(Parcel.java:2203)
                                                                      at android.os.Parcel.readParcelable(Parcel.java:2153)
                                                                      at android.os.Parcel.readValue(Parcel.java:2066)
                                                                      at android.os.Parcel.readArrayMapInternal(Parcel.java:2370)
                                                                      at android.os.Bundle.unparcel(Bundle.java:249)
                                                                      at android.os.Bundle.getSerializable(Bundle.java:1295)
                                                                      at android.content.Intent.getSerializableExtra(Intent.java:4710)
                                                                      at androidx.pluginmgr.environment.PluginInstrumentation.newActivity(PluginInstrumentation.java:52)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2106)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238) 
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:136) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5016) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                                                      at dalvik.system.NativeStart.main(Native Method) `

**Comment by christmasjason** [comment]
Add .so to your project. I had suffered the same problem, and solved by add all .so to my project.

**Comment by BriceChou** [comment]
1. 我觉得这不是没有添加 .so文件的错误。
2. 我个人认为，你这是在通过使用Intent传递实体类的时候报的错误，你可能直接传递了WeiboSDK里面的某个实体。
3. 你可以将WeiboSDK里面的实体全都实现Parcelable这个接口，然后再进行传递。
4. 请注意：一定要全部都实现，比如Status这个实体里面调用了Geo,User这些其他实体，如果这些其他实体没有实现这个接口，那么只有你的Status这个实体实现Parcelable接口也是没有用的。
5. 希望能帮助到你！

**Comment by jiaowenzheng** [comment]
就如你所说，可能是TextObject 对象的问题。

**Comment by kevin-nazgul** [comment]
昨天解决过一个一样的问题，我这边出现的原因是因为在AndroidManifest.xml里面有两个activity写了下面的Filter
```java
<intent-filter>
    <action android:name="com.sina.weibo.sdk.action.ACTION_SDK_REQ_ACTIVITY" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```
这样子分享触发后，由于有两个activity都满足，因此会在系统UI显示一个选择菜单，所以这个Intent会发往system:ui，造成这种堆栈。

解决办法：
保证只有一个activity有这种filter。

**Comment by ikkyu0319** [comment]
@kevin-nazgul 我这没有两个activity写 Filter

也报了 Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject ，求助~

**Comment by kevin-nazgul** [comment]
@ikkyu0319 你adb logcat > 1.txt，重现下，然后把日志文件给我看下。

**Comment by ikkyu0319** [comment]
发现 使用 weiboSDKCore_3.1.4.jar 会报错的~~ ，使用module里的jar 就没事了~

**Comment by jiaowenzheng** [comment]
呵呵，不会Umeng搞错了吧！！！

**Comment by donghuipei** [comment]
@BriceChou 我同意你的第一点和第二点，上面的异常log不是很全，下面是我的异常信息
java.lang.RuntimeException: Unable to start activity ComponentInfo{android/com.android.internal.app.ResolverActivity}: android.os.BadParcelableException: ClassNotFoundException  when unmarshalling: com.sina.weibo.sdk.api.TextObject
根据上面的异常信息，是在start ResolverActivity这个系统的activity的时候，反序列化TextObject这个对象的时候出现的异常，原因是系统的程序里面不能解析自定义的对象。所以我建议如果出现该异常的情况，可以检查手机是否安装了微博客户端，同时检查代码的逻辑中是否有打开ResolverActivity的intent，并且传递了TextObject对象。

**Comment by wangjiangtao** [comment]
初略看了下源码，感觉问题出在这里：
TextObject继承自BaseMediaObject，BaseMediaObject实现了Parcelable接口并且实现了方法，但是
TextObject在实现方法时没有调用父类方法导致的bug
感觉改成下面就行了
`public TextObject(Parcel var1) {
        super(var1);
        this.text = var1.readString();
    }
        .....
    public void writeToParcel(Parcel var1, int var2) {
        super.writeToParcel(var1,var2)
        var1.writeString(this.text);
    }`
