### ISSUE TITLE
 求助 ClassNotFoundException when unmarshalling: com.sina.weibo.sdk.api.TextObject

### ISSUE THREAD

**Issue by ikkyu0319** [sinaweibosdk/weibo_android_sdk#176]
`07-20 11:38:52.097 256-994/? I/SurfaceFlinger: id=3581 Removed ThareWeiBo (6/9)
07-20 11:38:52.097 256-2342/? I/SurfaceFlinger: id=3581 Removed ThareWeiBo (-2/9)
07-20 11:38:55.197 925-1021/? D/ActivityManager: isDeviceAdminActiveApp false :com.sina.weibo
07-20 11:38:55.197 925-1021/? D/ActivityManager: isAutoRunBlockedApp:: com.sina.weibo, Auto Run ON

07-20 11:38:55.227 925-1403/? E/Parcel: Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject
                                        java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
                                            at java.lang.Class.classForName(Native Method)
                                            at java.lang.Class.forName(Class.java:308)
                                            at java.lang.Class.forName(Class.java:272)
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
                                            at android.os.Parcel.readParcelable(Parcel.java:2239)
                                            at android.os.Parcel.readValue(Parcel.java:2146)
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                            at android.os.BaseBundle.getString(BaseBundle.java:918)
                                            at android.content.Intent.getStringExtra(Intent.java:5386)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1798)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1351)
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4821)
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4656)
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142)
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3166)
                                            at android.os.Binder.execTransact(Binder.java:446)
                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.api.TextObject" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                            at java.lang.Class.classForName(Native Method) 
                                            at java.lang.Class.forName(Class.java:308) 
                                            at java.lang.Class.forName(Class.java:272) 
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2275) 
                                            at android.os.Parcel.readParcelable(Parcel.java:2239) 
                                            at android.os.Parcel.readValue(Parcel.java:2146) 
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479) 
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                            at android.os.BaseBundle.getString(BaseBundle.java:918) 
                                            at android.content.Intent.getStringExtra(Intent.java:5386) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1798) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1351) 
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4821) 
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4656) 
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142) 
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3166) 
                                            at android.os.Binder.execTransact(Binder.java:446) 
                                            Suppressed: java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
                                            at java.lang.Class.classForName(Native Method)
                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                    ... 18 more
                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

07-20 11:38:55.227 925-1403/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname com.sina.weibo
07-20 11:38:55.297 925-1021/? D/ActivityManager: isDeviceAdminActiveApp false :com.sina.weibo
07-20 11:38:55.297 925-1021/? D/ActivityManager: isAutoRunBlockedApp:: com.sina.weibo, Auto Run ON
07-20 11:38:55.307 3575-3575/? W/ContextImpl: Implicit intents with startService are not safe: Intent { act=com.sina.weibo.action.SEND_QUEUE } android.content.ContextWrapper.bindService:559 com.sina.weibo.EditActivity.a_:1983 com.sina.weibo.BaseActivity.d:425 
07-20 11:38:55.337 925-1408/? D/ActivityManager: bindService callerProcessName:com.sina.weibo, calleePkgName: com.sina.weibo, action: null
07-20 11:38:55.427 925-1055/? I/ActivityManager: Displayed com.sina.weibo/.EditActivity: +183ms (total +253ms)
07-20 11:38:55.447 925-1130/? I/MultiPhoneWindowManager: Changed -> mCurrentInputMethodTarget : Window{2de7d58e u0 com.sina.weibo/com.sina.weibo.EditActivity}
07-20 11:38:55.447 925-1330/? D/ActivityManager: isDeviceAdminActiveApp false :com.sina.weibo
07-20 11:38:55.447 925-1330/? D/ActivityManager: isAutoRunBlockedApp:: com.sina.weibo, Auto Run ON
07-20 11:38:55.507 3575-7227/? W/System.err:     at com.sina.weibo.models.JsonPushResult.initFromJsonObject(JsonPushResult.java:773)
07-20 11:38:55.507 3575-7227/? W/System.err:     at com.sina.weibo.models.JsonDataObject.initFromJsonString(JsonDataObject.java:49)
07-20 11:38:55.507 3575-7227/? W/System.err:     at com.sina.weibo.models.JsonDataObject.<init>(JsonDataObject.java:23)
07-20 11:38:55.507 3575-7227/? W/System.err:     at com.sina.weibo.models.JsonPushResult.<init>(JsonPushResult.java:556)
07-20 11:38:55.507 3575-7227/? W/System.err:     at com.sina.weibo.net.f.a(NetEngine.java:4109)
07-20 11:38:55.507 3575-7227/? W/System.err:     at com.sina.weibo.SwitchStateReceiver.a(SwitchStateReceiver.java:100)
07-20 11:38:55.507 3575-7227/? W/System.err:     at com.sina.weibo.aeh.run(SwitchStateReceiver.java:58)
07-20 11:38:55.707 925-1055/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{2fe3a4d5 u0 com.sina.weibo/.EditActivity t260} time:54853054
07-20 11:39:00.297 925-1403/? E/Parcel: Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject
                                        java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
                                            at java.lang.Class.classForName(Native Method)
                                            at java.lang.Class.forName(Class.java:308)
                                            at java.lang.Class.forName(Class.java:272)
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
                                            at android.os.Parcel.readParcelable(Parcel.java:2239)
                                            at android.os.Parcel.readValue(Parcel.java:2146)
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                            at android.os.BaseBundle.getString(BaseBundle.java:918)
                                            at android.content.Intent.getStringExtra(Intent.java:5386)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1798)
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1351)
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4821)
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4656)
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142)
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3166)
                                            at android.os.Binder.execTransact(Binder.java:446)
                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.api.TextObject" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                            at java.lang.Class.classForName(Native Method) 
                                            at java.lang.Class.forName(Class.java:308) 
                                            at java.lang.Class.forName(Class.java:272) 
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2275) 
                                            at android.os.Parcel.readParcelable(Parcel.java:2239) 
                                            at android.os.Parcel.readValue(Parcel.java:2146) 
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479) 
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                            at android.os.BaseBundle.getString(BaseBundle.java:918) 
                                            at android.content.Intent.getStringExtra(Intent.java:5386) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1798) 
                                            at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1351) 
                                            at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4821) 
                                            at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4656) 
                                            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142) 
                                            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3166) 
                                            at android.os.Binder.execTransact(Binder.java:446) 
                                            Suppressed: java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
                                            at java.lang.Class.classForName(Native Method)
                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                    ... 18 more
                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
07-20 11:39:00.317 925-1490/? W/ActivityManager: Duplicate finish request for ActivityRecord{2fe3a4d5 u0 com.sina.weibo/.EditActivity t260 f}
07-20 11:39:00.347 925-1021/? D/ActivityManager: isDeviceAdminActiveApp false :com.sina.weibo
07-20 11:39:00.347 925-1021/? D/ActivityManager: isAutoRunBlockedApp:: com.sina.weibo, Auto Run ON
07-20 11:39:00.387 256-256/? I/SurfaceFlinger: id=3588 createSurf (1080x1920),1 flag=4, ThareWeiBo
07-20 11:39:05.397 925-1055/? I/ActivityManager: Displayed com.qyer.android.plan/.share.ShareWeiBo: +5s81ms
07-20 11:39:05.787 925-1055/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{1d64a9ab u0 com.qyer.android.plan/.share.ShareWeiBo t260} time:54863131
07-20 11:39:05.847 925-1021/? D/ActivityManager: isDeviceAdminActiveApp false :com.sina.weibo
07-20 11:39:05.847 925-1021/? D/ActivityManager: isAutoRunBlockedApp:: com.sina.weibo, Auto Run ON
07-20 11:39:05.937 925-1490/? D/ActivityManager: isDeviceAdminActiveApp false :com.sina.weibo
07-20 11:39:05.937 925-1490/? D/ActivityManager: isAutoRunBlockedApp:: com.sina.weibo, Auto Run ON
07-20 11:39:06.327 3575-7315/? W/System.err:     at com.sina.weibo.models.JsonPushResult.initFromJsonObject(JsonPushResult.java:773)
07-20 11:39:06.327 3575-7315/? W/System.err:     at com.sina.weibo.models.JsonDataObject.initFromJsonString(JsonDataObject.java:49)
07-20 11:39:06.327 3575-7315/? W/System.err:     at com.sina.weibo.models.JsonDataObject.<init>(JsonDataObject.java:23)
07-20 11:39:06.327 3575-7315/? W/System.err:     at com.sina.weibo.models.JsonPushResult.<init>(JsonPushResult.java:556)
07-20 11:39:06.327 3575-7315/? W/System.err:     at com.sina.weibo.net.f.a(NetEngine.java:4109)
07-20 11:39:06.327 3575-7315/? W/System.err:     at com.sina.weibo.SwitchStateReceiver.a(SwitchStateReceiver.java:100)
07-20 11:39:06.327 3575-7315/? W/System.err:     at com.sina.weibo.aeh.run(SwitchStateReceiver.java:58)
`

**Comment by ikkyu0319** [comment]
求助

**Comment by BriceChou** [comment]
@ikkyu0319 
你这个是使用了官方的jar包后报错的，还是导入了Module后，引用了它的API以后报的错误啊？

**Comment by ikkyu0319** [comment]
我使用 官方的weiboSDKCore_3.1.4.jar ，没有使用他的Module，

我发现，改为module里的 jar包就不报错了!!!
@BriceChou

**Comment by getpro** [comment]
同问，怎么解决？友盟的demo也是这个问题，之前还能使用，这几天就出这个问题了

**Comment by BriceChou** [comment]
@ ikkyu0319 
好吧！我以前使用 Module后，报过这样的错误。
我没有用过官方的哪个jar包，那就不清楚了，不好意思哈！

**Comment by jianyifu** [comment]
我也出现了同样的问题，请问解决了么

**Comment by sunguotao** [comment]
请问怎么解啊？fuck sina

**Comment by lb1207087645** [comment]
@ikkyu0319 module是哪个，我是从官方下的sdk包，我用的是Sample libs下的ShareSDK-SinaWeibo-3.0.0.jar 包报错了，不知道你说的module是哪个的？
