### ISSUE TITLE
分享报错Class not found when unmarshalling: com.sina.weibo.sdk.api.ImageObject

### ISSUE THREAD

**Issue by getpro** [sinaweibosdk/weibo_android_sdk#177]
**SDK版本：3.1.4**

**代码：**

<pre><code class="java">
WeiboMessage weiboMessage = new WeiboMessage();
ImageObject imageObject = new ImageObject();
Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher);
imageObject.setImageObject(bitmap);
weiboMessage.mediaObject = imageObject;
SendMessageToWeiboRequest request = new SendMessageToWeiboRequest();
request.transaction = String.valueOf(System.currentTimeMillis());
request.message = weiboMessage;
mWeiboShareAPI.sendRequest(SinaActivity.this, request);
</code></pre>

**错误：**

<pre><code>
Class not found when unmarshalling: com.sina.weibo.sdk.api.ImageObject
java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.ImageObject
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:251)
    at java.lang.Class.forName(Class.java:216)
    at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
    at android.os.Parcel.readParcelable(Parcel.java:2097)
    at android.os.Parcel.readValue(Parcel.java:2013)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
    at android.os.Bundle.unparcel(Bundle.java:249)
    at android.os.Bundle.getInt(Bundle.java:994)
    at android.content.Intent.getIntExtra(Intent.java:4571)
    at fuck.g.b(Unknown Source)
    at fuck.g.a(Unknown Source)
    at fuck.g.transact(Unknown Source)
    at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2116)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419)
    at android.app.Activity.startActivityForResult(Activity.java:3537)
    at android.app.Activity.startActivityForResult(Activity.java:3498)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
    at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.launchWeiboActivity(WeiboShareAPIImpl.java:502)
    at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.sendRequest(WeiboShareAPIImpl.java:312)
    at com.rskj.qlgshop.activity.ActivityProductDetail$3.onLoadingComplete(ActivityProductDetail.java:525)
    at com.nostra13.universalimageloader.core.DisplayBitmapTask.run(DisplayBitmapTask.java:72)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5120)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.NoClassDefFoundError: com/sina/weibo/sdk/api/ImageObject
    at java.lang.Class.classForName(Native Method) 
    at java.lang.Class.forName(Class.java:251) 
    at java.lang.Class.forName(Class.java:216) 
    at android.os.Parcel.readParcelableCreator(Parcel.java:2133) 
    at android.os.Parcel.readParcelable(Parcel.java:2097) 
    at android.os.Parcel.readValue(Parcel.java:2013) 
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2314) 
    at android.os.Bundle.unparcel(Bundle.java:249) 
    at android.os.Bundle.getInt(Bundle.java:994) 
    at android.content.Intent.getIntExtra(Intent.java:4571) 
    at fuck.g.b(Unknown Source) 
    at fuck.g.a(Unknown Source) 
    at fuck.g.transact(Unknown Source) 
    at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2116) 
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419) 
    at android.app.Activity.startActivityForResult(Activity.java:3537) 
    at android.app.Activity.startActivityForResult(Activity.java:3498) 
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842) 
    at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.launchWeiboActivity(WeiboShareAPIImpl.java:502) 
    at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.sendRequest(WeiboShareAPIImpl.java:312) 
    at com.rskj.qlgshop.activity.ActivityProductDetail$3.onLoadingComplete(ActivityProductDetail.java:525) 
    at com.nostra13.universalimageloader.core.DisplayBitmapTask.run(DisplayBitmapTask.java:72) 
    at android.os.Handler.handleCallback(Handler.java:733) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.app.ActivityThread.main(ActivityThread.java:5120) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634) 
    at dalvik.system.NativeStart.main(Native Method) 
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.api.ImageObject" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
    at java.lang.Class.classForName(Native Method) 
    at java.lang.Class.forName(Class.java:251) 
    at java.lang.Class.forName(Class.java:216) 
    at android.os.Parcel.readParcelableCreator(Parcel.java:2133) 
    at android.os.Parcel.readParcelable(Parcel.java:2097) 
    at android.os.Parcel.readValue(Parcel.java:2013) 
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2314) 
    at android.os.Bundle.unparcel(Bundle.java:249) 
    at android.os.Bundle.getInt(Bundle.java:994) 
    at android.content.Intent.getIntExtra(Intent.java:4571) 
    at fuck.g.b(Unknown Source) 
    at fuck.g.a(Unknown Source) 
    at fuck.g.transact(Unknown Source) 
    at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2116) 
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419) 
    at android.app.Activity.startActivityForResult(Activity.java:3537) 
    at android.app.Activity.startActivityForResult(Activity.java:3498) 
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842) 
    at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.launchWeiboActivity(WeiboShareAPIImpl.java:502) 
    at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.sendRequest(WeiboShareAPIImpl.java:312) 
    at com.rskj.qlgshop.activity.ActivityProductDetail$3.onLoadingComplete(ActivityProductDetail.java:525) 
    at com.nostra13.universalimageloader.core.DisplayBitmapTask.run(DisplayBitmapTask.java:72) 
    at android.os.Handler.handleCallback(Handler.java:733) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.app.ActivityThread.main(ActivityThread.java:5120) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634) 
    at dalvik.system.NativeStart.main(Native Method) 
</code></pre>

**Comment by BriceChou** [comment]
@getpro 
1. 如果您使用的是导入 Moudle后,引用了这个ImageObject实体类，我个人认为，您在传递这个ImageObject时，ImageObject没有序列化。
2. 具体您可以在当前package下，创建一个BaseEntity Java类
```java
package com.sina.weibo.sdk.openapi.models;
import java.io.Serializable;
public class BaseEntity implements Serializable{
}
```
之后将 
```java
ImageObject extends BaseEntity
```
即可解决问题。
3. 如果您使用的是官方的jar包，那我就不知道怎么解决了。但是您可以考虑使用[ImageLoader](https://github.com/nostra13/Android-Universal-Image-Loader)这个第三方插件进行处理以后再分享。
以上，希望能够帮助到您！

**Comment by getpro** [comment]
@BriceChou 用的是官方的jar包，可能是SDK服务端有问题？反正我什么都没动，，过几天又没问题了，神奇的新浪分享⊙﹏⊙
