### ISSUE TITLE
Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked window

### ISSUE THREAD

**Issue by junzew** [sinaweibosdk/weibo_android_sdk#179]
通过Web分享时, 点击文字编辑框打开软键盘后点左上角的关闭，软键盘不能关闭且得到如下错误信息：

android.view.WindowLeaked: Activity com.sina.weibo.sdk.component.WeiboSdkBrowser has leaked window org.chromium.content.browser.input.PopupTouchHandleDrawable{1c7e0aa0 I.ED.... ........ 0,0-141,174} that was originally added here
                                                                  at android.view.ViewRootImpl.<init>(ViewRootImpl.java:465)
                                                                  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:277)
                                                                  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                  at android.widget.PopupWindow.invokePopup(PopupWindow.java:1107)
                                                                  at android.widget.PopupWindow.showAtLocation(PopupWindow.java:914)
                                                                  at android.widget.PopupWindow.showAtLocation(PopupWindow.java:873)
                                                                  at org.chromium.content.browser.input.PopupTouchHandleDrawable.show(PopupTouchHandleDrawable.java:431)
                                                                  at org.chromium.android_webview.AwContents.nativeOnDraw(Native Method)
                                                                  at org.chromium.android_webview.AwContents.access$4500(AwContents.java:95)
                                                                  at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDraw(AwContents.java:2907)
                                                                  at org.chromium.android_webview.AwContents.onDraw(AwContents.java:1253)
                                                                  at com.android.webview.chromium.WebViewChromium.onDraw(WebViewChromium.java:1739)
                                                                  at android.webkit.WebView.onDraw(WebView.java:2406)
                                                                  at android.view.View.draw(View.java:16219)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15139)
                                                                  at android.view.View.getDisplayList(View.java:15162)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15099)
                                                                  at android.view.View.getDisplayList(View.java:15162)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15099)
                                                                  at android.view.View.getDisplayList(View.java:15162)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15099)
                                                                  at android.view.View.getDisplayList(View.java:15162)
                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3687)
                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3666)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15099)
                                                                  at android.view.View.getDisplayList(View.java:15162)
                                                                  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
                                                                  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
                                                                  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
                                                                  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
                                                                  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                  at 
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:145)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by BriceChou** [comment]
@junzew 
我个人认为这个问题跟WeiboSDK 的关系不大，理论上说应该是Android的窗体溢出问题。
具体您可以查查 “android.view.WindowLeaked” 这个问题的解决方案。
我给您推荐几篇文章：
1. [关于android.view.WindowLeaked异常的解决方案](http://www.cnblogs.com/error404/archive/2011/11/21/2256953.html)
2. [关于android.view.WindowLeaked异常的解决方案2](http://blog.csdn.net/howlaa/article/details/17500371)
以上，希望能够帮助到您！
