### ISSUE TITLE
Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject

### ISSUE THREAD

**Issue by yuruxuan** [sinaweibosdk/weibo_android_sdk#187]
不管是代码里的Jar还是3.1.4的Jar都报错，好像有人问过这问题了，但是并没有解决

08-17 12:40:57.633 4030-4030/? E/Parcel: Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject
                                         java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
                                             at android.os.Parcel.readParcelable(Parcel.java:2358)
                                             at android.os.Parcel.readValue(Parcel.java:2264)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.Bundle.getParcelable(Bundle.java:786)
                                             at android.content.Intent.getParcelableExtra(Intent.java:5381)
                                             at android.app.Activity.getReferrer(Activity.java:4748)
                                             at com.android.internal.app.ResolverActivity.getReferrerPackageName(ResolverActivity.java:345)
                                             at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:248)
                                             at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:198)
                                             at android.app.Activity.performCreate(Activity.java:6303)
                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                             at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:148)
                                             at android.app.ActivityThread.main(ActivityThread.java:5438)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.api.TextObject" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2404) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2358) 
                                             at android.os.Parcel.readValue(Parcel.java:2264) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.Bundle.getParcelable(Bundle.java:786) 
                                             at android.content.Intent.getParcelableExtra(Intent.java:5381) 
                                             at android.app.Activity.getReferrer(Activity.java:4748) 
                                             at com.android.internal.app.ResolverActivity.getReferrerPackageName(ResolverActivity.java:345) 
                                             at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:248) 
                                             at com.android.internal.app.ResolverActivity.onCreate(ResolverActivity.java:198) 
                                             at android.app.Activity.performCreate(Activity.java:6303) 
                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376) 
                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                             at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                             at android.os.Looper.loop(Looper.java:148) 
                                             at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                             at java.lang.reflect.Method.invoke(Native Method) 
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                            Suppressed: java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                    ... 26 more
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by yuruxuan** [comment]
> 昨天解决过一个一样的问题，我这边出现的原因是因为在AndroidManifest.xml里面有两个activity写了下面的Filter

<intent-filter>
    <action android:name="com.sina.weibo.sdk.action.ACTION_SDK_REQ_ACTIVITY" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
这样子分享触发后，由于有两个activity都满足，因此会在系统UI显示一个选择菜单，所以这个Intent会发往system:ui，造成这种堆栈。

解决办法：
保证只有一个activity有这种filter。

引用[https://github.com/sinaweibosdk/weibo_android_sdk/issues/162](url)

**Comment by Freerain9** [comment]
我也遇到了类似的问题  我是 将新浪微博插件化  加载的时候  必现这个问题Class not found when unmarshalling: com.sina.weibo.sdk.api.VideoObject，弄的很郁闷
