### ISSUE TITLE
java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject

### ISSUE THREAD

**Issue by flipperji** [sinaweibosdk/weibo_android_sdk#199]
前两天微博分享还可以的，今天点微博分享，直接闪退
`Class not found when unmarshalling: com.sina.weibo.sdk.api.TextObject
                                         java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.TextObject
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:308)
                                             at java.lang.Class.forName(Class.java:272)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
                                             at android.os.Parcel.readParcelable(Parcel.java:2239)
                                             at android.os.Parcel.readValue(Parcel.java:2146)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getString(BaseBundle.java:918)
                                             at android.content.Intent.getStringExtra(Intent.java:5386)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1799)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1352)
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4888)
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4725)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3225)
                                             at android.os.Binder.execTransact(Binder.java:446)`

**Comment by zhuhuang521** [comment]
已经收录，等待解决

**Comment by angularzues** [comment]
应该是混淆的问题吧
