### ISSUE TITLE
3.1.1 Web授权时 无法授权 网址出现 && 导致字符串出错 （原因 scope 为空）

### ISSUE THREAD

**Issue by vhly** [sinaweibosdk/weibo_android_sdk#219]
经过动态调试，如果 scope 为空 那么授权时 程序崩溃

                                                                    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                        at com.sina.weibo.sdk.utils.Utility.decodeUrl(Utility.java:87)
                                                                        at com.sina.weibo.sdk.utils.Utility.parseUrl(Utility.java:56)
                                                                        at com.sina.weibo.sdk.component.AuthWeiboWebViewClient.handleRedirectUrl(AuthWeiboWebViewClient.java:107)
                                                                        at com.sina.weibo.sdk.component.AuthWeiboWebViewClient.onPageStarted(AuthWeiboWebViewClient.java:39)
                                                                        at com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted(WebViewContentsClientAdapter.java:510)
                                                                        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:144)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5491)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by foreverflame** [comment]
请问这个问题怎么解决
