### ISSUE TITLE
android.os.BadParcelableException TextObject

### ISSUE THREAD

**Issue by smallSohoSolo** [sinaweibosdk/weibo_android_sdk#254]
Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.sina.weibo.sdk.api.TextObject
       at android.os.Parcel.readException(Parcel.java:1548)
       at android.os.Parcel.readException(Parcel.java:1499)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2650)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1558)
       at android.app.Activity.startActivityForResult(Activity.java:3830)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
       at android.app.Activity.startActivityForResult(Activity.java:3787)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.launchWeiboActivity(WeiboShareAPIImpl.java:491)
       at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.sendRequest(WeiboShareAPIImpl.java:310)
       at com.ss.android.ugc.aweme.common.share.WeiboSDKUrlSharelet.share(WeiboSDKUrlSharelet.java:60)
       at com.ss.android.ugc.aweme.feed.share.AwemeShareHelper.share(AwemeShareHelper.java:35)
       at com.ss.android.ugc.aweme.feed.ui.UploadSuccessPopView.onClick_aroundBody0(UploadSuccessPopView.java:173)
       at com.ss.android.ugc.aweme.feed.ui.UploadSuccessPopView$AjcClosure1.run(UploadSuccessPopView.java:1)
       at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
       at com.ss.android.ugc.aweme.aspect.NoDoubleClickAspect.onClickListener(NoDoubleClickAspect.java:33)
       at com.ss.android.ugc.aweme.feed.ui.UploadSuccessPopView.onClick(UploadSuccessPopView.java:127)
       at android.view.View.performClick(View.java:4918)
       at android.view.View$PerformClick.run(View.java:20399)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5869)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by Jungerr** [comment]
+1
有解决方案吗？
