### ISSUE TITLE
新版SDK导致UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jinqian** [sinaweibosdk/weibo_android_sdk#260]
使用版本：
```
compile 'com.sina.weibo.sdk:core:2.0.1:openDefaultRelease@aar'
```
Error logs:
```
04-26 14:11:45.685 23597-23597/ D/ApplicationLoaders: ignored Vulkan layer search path /data/app/com.sina.weibo-1/lib/arm:/data/app/com.sina.weibo-1/base.apk!/lib/armeabi for namespace 0x7b310fb0f0
04-26 14:11:45.724 23597-23625/ W/art: No such thread for suspend: 0x7b17862bd8:Thread-15
04-26 14:11:45.742 23597-23738/ I/art: Rejecting re-init on previously-failed class java.lang.Class<com.sina.weibo.sdk.net.HttpManager>: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/-2/base.apk", zip file "/data/app/-2/split_lib_dependencies_apk.apk", zip file "/data/app/-2/split_lib_slice_0_apk.apk", zip file "/data/app/-2/split_lib_slice_1_apk.apk", zip file "/data/app/-2/split_lib_slice_2_apk.apk", zip file "/data/app/-2/split_lib_slice_3_apk.apk", zip file "/data/app/-2/split_lib_slice_4_apk.apk", zip file "/data/app/-2/split_lib_slice_5_apk.apk", zip file "/data/app/-2/split_lib_slice_6_apk.apk", zip file "/data/app/-2/split_lib_slice_7_apk.apk", zip file "/data/app/cn.fashicon.
04-26 14:11:45.742 23597-23738/ I/art: (Throwable with no stack trace)
04-26 14:11:45.851 23597-23732/ E/AndroidRuntime: FATAL EXCEPTION: Thread-13
Process: , PID: 23597
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/-2/base.apk", zip file "/data/app/-2/split_lib_dependencies_apk.apk", zip file "/data/app/-2/split_lib_slice_0_apk.apk", zip file "/data/app/-2/split_lib_slice_1_apk.apk", zip file "/data/app/-2/split_lib_slice_2_apk.apk", zip file "/data/app/-2/split_lib_slice_3_apk.apk", zip file "/data/app/-2/split_lib_slice_4_apk.apk", zip file "/data/app/-2/split_lib_slice_5_apk.apk", zip file "/data/app/-2/split_lib_slice_6_apk.apk", zip file "/data/app/-2/split_lib_slice_7_apk.apk", zip file "/data/app/-2/split_lib_slice_8_apk.apk", zip file "/data/app/-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/-2/lib/arm64, /data/app/-2/base.apk!/lib/arm64-v8a, /data/app/-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libweibosdkcore.so"
  at java.lang.Runtime.loadLibrary0(Runtime.java:984)
  at java.lang.System.loadLibrary(System.java:1562)
  at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:43)
  at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:63)
  at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:400)
  at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
  at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:232)
  at java.lang.Thread.run(Thread.java:761)
```
FYI，应该是64bit device上的问题，我的测试机型为Nexus 5X。这个问题貌似两年前就存在了，到现在都没有修正：https://github.com/sinaweibosdk/weibo_android_sdk/issues/88 :(

FYI again，我的app使用了multidex。

**Comment by jinqian** [comment]
FYI, workaround with `splits` can prevent the crash: http://stackoverflow.com/a/33928159

**Comment by zhuhuang521** [comment]
所有版本的so已经同步到so文件夹中

**Comment by jinqian** [comment]
@zhuhuang521 
<img width="619" alt="screen shot 2017-04-27 at 11 36 11" src="https://cloud.githubusercontent.com/assets/1364907/25477547/375f187c-2b3e-11e7-83e1-7f282ba82802.png">
缺少`arm64-v8a`和`x86_64`的库好吗……

FYI：https://developer.android.com/ndk/guides/abis.html

你们可以多测试一下吗，integration新版的过程各种不顺利 :(

**Comment by zhuhuang521** [comment]
@jinqian sdk主工程需要尽量保证大小不能太大，所以内部只是提供了3个主流平台的so，github已经在so目录下https://github.com/sinaweibosdk/weibo_android_sdk/tree/master/so 上传了平台的版本，如果你的程序需要支持全部平台，可以自行添加到你的工程目录中。

**Comment by jinqian** [comment]
@zhuhuang521 okay，那可以请你们至少更新文档说明这点吗？不然会有其他很多人遇到同样的问题。而且我并不同意这个所谓的3个主流的平台，所有主流的lib如果有Native的部分，都会包括`arm64-v8a`和`x86_64`的。

**Comment by WanghongLin** [comment]
现在`arm64-v8a`是非常主流的平台，麻烦添加进去。

既然要手动添加，又多了一些`jniLibs/xxxx`文件夹，这和原来没有用aar没多少区别。

其他包含native library的库，都会包含所有的arch的，微博既然也做成了aar的形式了，就应该和其他的也保持一致吧。

sdk的工程大小也不是这样子保证的。

微博sdk的开发者考虑太多了。

大小最终还是由app这边考虑和处理的。可以决定是否split成不同的arch下的apk，或者exclude某些arch的实现不那么大的。

**Comment by FrancisShi** [comment]
呵呵哒
