### ISSUE TITLE
v2.0.1 SDK授权成功后onActivityResult没有回调

### ISSUE THREAD

**Issue by jinqian** [sinaweibosdk/weibo_android_sdk#263]
Follow了官方最新的文档和demo进行了一下的integration

- 使用版本：
```
compile 'com.sina.weibo.sdk:core:2.0.1:openDefaultRelease@aar'
```
- 在Application class里初始化了WbSDK
```
WbSdk.install(this, new AuthInfo(this, BuildConfig.WEIBO_APP_ID, BuildConfig.WEIBO_REDIRECTION_URL, Constant.WEIBO_SCOPE));
```
- 在LoginActivity class里初始化了SsoHandler
```
weiboSSOHandler = new SsoHandler(LoginActivity.this);
```
- OnClick event里调用了`authorize`方法
```
    @OnClick(R.id.btn_login_weibo_container)
    public void loginWithWeibo() {
        weiboSSOHandler.authorize(this);
    }
```
- override了`onActivityResult`方法:
```
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (weiboSSOHandler != null) {
            weiboSSOHandler.authorizeCallBack(requestCode, resultCode, data);
        }
    }
```

我用自己的`debug.keystore` sign了我的app，在网站上也输入了我的packageName & MD5 signature，authorize方法可以正确打开weibo app进行授权，但一旦点击授权之后并没有回到我自己的app的LoginActivity而是直接退出了，onActivityResult完全没有被fire。鉴于我在64bit的device上遇到了`.so`库文件的loading问题(#260)，是不是AIDL的实现问题？

测试device:
- Nexus 5x Android Nougat (7.1.2)
- Samsung S6 Android Nougat (7.0)

**Comment by jinqian** [comment]
logcat里我发现了这些error log
```
04-27 14:47:09.562 32314-32314/? W/System.err: java.lang.SecurityException: getCellLocation: Neither user 10250 nor current process has android.permission.ACCESS_COARSE_LOCATION.
04-27 14:47:09.563 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1693)
04-27 14:47:09.563 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1646)
04-27 14:47:09.563 32314-32314/? W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getCellLocation(ITelephony.java:3251)
04-27 14:47:09.563 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getCellLocation(TelephonyManager.java:1065)
04-27 14:47:09.563 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.g(AdHelper.java:134)
04-27 14:47:09.563 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.a(AdHelper.java:47)
04-27 14:47:09.563 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.a(DianXinSdkUtils.java:84)
04-27 14:47:09.563 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.b(DianXinSdkUtils.java:271)
04-27 14:47:09.563 32314-32314/? W/System.err:     at com.sina.weibo.ScreenOrientationBaseActivity.onStop(ScreenOrientationBaseActivity.java:238)
04-27 14:47:09.563 32314-32314/? W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
04-27 14:47:09.563 32314-32314/? W/System.err:     at com.sina.weibo.bundlemanager.c.a.callActivityOnStop(InstrumentationHook.java:376)
04-27 14:47:09.563 32314-32314/? W/System.err:     at android.app.Activity.performStop(Activity.java:7138)
04-27 14:47:09.563 32314-32314/? W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4596)
04-27 14:47:09.563 32314-32314/? W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4662)
04-27 14:47:09.563 32314-32314/? W/System.err:     at android.app.ActivityThread.-wrap7(ActivityThread.java)
04-27 14:47:09.564 32314-32314/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
04-27 14:47:09.564 32314-32314/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 14:47:09.564 32314-32314/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-27 14:47:09.564 32314-32314/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6688)
04-27 14:47:09.564 32314-32314/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-27 14:47:09.564 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
04-27 14:47:09.564 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-27 14:47:09.570 32314-32314/? W/System.err: java.lang.SecurityException: getDeviceId: Neither user 10250 nor current process has android.permission.READ_PHONE_STATE.
04-27 14:47:09.570 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1693)
04-27 14:47:09.570 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1646)
04-27 14:47:09.570 32314-32314/? W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:5091)
04-27 14:47:09.570 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:913)
04-27 14:47:09.570 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.j(AdHelper.java:373)
04-27 14:47:09.571 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.b(AdHelper.java:51)
04-27 14:47:09.571 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.a(DianXinSdkUtils.java:86)
04-27 14:47:09.571 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.b(DianXinSdkUtils.java:271)
04-27 14:47:09.572 32314-32314/? W/System.err:     at com.sina.weibo.ScreenOrientationBaseActivity.onStop(ScreenOrientationBaseActivity.java:238)
04-27 14:47:09.572 32314-32314/? W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
04-27 14:47:09.572 32314-32314/? W/System.err:     at com.sina.weibo.bundlemanager.c.a.callActivityOnStop(InstrumentationHook.java:376)
04-27 14:47:09.572 32314-32314/? W/System.err:     at android.app.Activity.performStop(Activity.java:7138)
04-27 14:47:09.572 32314-32314/? W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4596)
04-27 14:47:09.572 32314-32314/? W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4662)
04-27 14:47:09.572 32314-32314/? W/System.err:     at android.app.ActivityThread.-wrap7(ActivityThread.java)
04-27 14:47:09.572 32314-32314/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
04-27 14:47:09.572 32314-32314/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 14:47:09.572 32314-32314/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-27 14:47:09.572 32314-32314/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6688)
04-27 14:47:09.572 32314-32314/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-27 14:47:09.572 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
04-27 14:47:09.572 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-27 14:47:09.578 32314-32314/? W/System.err: java.lang.SecurityException: getSubscriberId: Neither user 10250 nor current process has android.permission.READ_PHONE_STATE.
04-27 14:47:09.578 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1693)
04-27 14:47:09.578 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1646)
04-27 14:47:09.578 32314-32314/? W/System.err:     at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getSubscriberIdForSubscriber(IPhoneSubInfo.java:800)
04-27 14:47:09.579 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2581)
04-27 14:47:09.579 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2562)
04-27 14:47:09.579 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.i(AdHelper.java:348)
04-27 14:47:09.579 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.b(AdHelper.java:51)
04-27 14:47:09.579 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.a(DianXinSdkUtils.java:86)
04-27 14:47:09.579 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.b(DianXinSdkUtils.java:271)
04-27 14:47:09.579 32314-32314/? W/System.err:     at com.sina.weibo.ScreenOrientationBaseActivity.onStop(ScreenOrientationBaseActivity.java:238)
04-27 14:47:09.580 32314-32314/? W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
04-27 14:47:09.580 32314-32314/? W/System.err:     at com.sina.weibo.bundlemanager.c.a.callActivityOnStop(InstrumentationHook.java:376)
04-27 14:47:09.580 32314-32314/? W/System.err:     at android.app.Activity.performStop(Activity.java:7138)
04-27 14:47:09.580 32314-32314/? W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4596)
04-27 14:47:09.580 32314-32314/? W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4662)
04-27 14:47:09.580 32314-32314/? W/System.err:     at android.app.ActivityThread.-wrap7(ActivityThread.java)
04-27 14:47:09.580 32314-32314/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
04-27 14:47:09.580 32314-32314/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 14:47:09.580 32314-32314/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-27 14:47:09.580 32314-32314/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6688)
04-27 14:47:09.581 32314-32314/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-27 14:47:09.581 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
04-27 14:47:09.581 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-27 14:47:09.591 32314-32314/? W/System.err: java.lang.SecurityException: getCellLocation: Neither user 10250 nor current process has android.permission.ACCESS_COARSE_LOCATION.
04-27 14:47:09.592 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1693)
04-27 14:47:09.592 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1646)
04-27 14:47:09.592 32314-32314/? W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getCellLocation(ITelephony.java:3251)
04-27 14:47:09.592 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getCellLocation(TelephonyManager.java:1065)
04-27 14:47:09.592 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.e(AdHelper.java:80)
04-27 14:47:09.592 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.a(DianXinSdkUtils.java:89)
04-27 14:47:09.592 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.b(DianXinSdkUtils.java:271)
04-27 14:47:09.592 32314-32314/? W/System.err:     at com.sina.weibo.ScreenOrientationBaseActivity.onStop(ScreenOrientationBaseActivity.java:238)
04-27 14:47:09.592 32314-32314/? W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
04-27 14:47:09.592 32314-32314/? W/System.err:     at com.sina.weibo.bundlemanager.c.a.callActivityOnStop(InstrumentationHook.java:376)
04-27 14:47:09.592 32314-32314/? W/System.err:     at android.app.Activity.performStop(Activity.java:7138)
04-27 14:47:09.592 32314-32314/? W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4596)
04-27 14:47:09.592 32314-32314/? W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4662)
04-27 14:47:09.592 32314-32314/? W/System.err:     at android.app.ActivityThread.-wrap7(ActivityThread.java)
04-27 14:47:09.593 32314-32314/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
04-27 14:47:09.593 32314-32314/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 14:47:09.593 32314-32314/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-27 14:47:09.593 32314-32314/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6688)
04-27 14:47:09.593 32314-32314/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-27 14:47:09.593 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
04-27 14:47:09.593 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-27 14:47:09.606 32314-32314/? W/System.err: java.lang.SecurityException: getCellLocation: Neither user 10250 nor current process has android.permission.ACCESS_COARSE_LOCATION.
04-27 14:47:09.607 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1693)
04-27 14:47:09.607 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1646)
04-27 14:47:09.607 32314-32314/? W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getCellLocation(ITelephony.java:3251)
04-27 14:47:09.607 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getCellLocation(TelephonyManager.java:1065)
04-27 14:47:09.607 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.g(AdHelper.java:134)
04-27 14:47:09.607 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.a(AdHelper.java:47)
04-27 14:47:09.607 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.a(DianXinSdkUtils.java:84)
04-27 14:47:09.607 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.b(DianXinSdkUtils.java:274)
04-27 14:47:09.609 32314-32314/? W/System.err:     at com.sina.weibo.ScreenOrientationBaseActivity.onStop(ScreenOrientationBaseActivity.java:238)
04-27 14:47:09.610 32314-32314/? W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
04-27 14:47:09.610 32314-32314/? W/System.err:     at com.sina.weibo.bundlemanager.c.a.callActivityOnStop(InstrumentationHook.java:376)
04-27 14:47:09.610 32314-32314/? W/System.err:     at android.app.Activity.performStop(Activity.java:7138)
04-27 14:47:09.610 32314-32314/? W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4596)
04-27 14:47:09.610 32314-32314/? W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4662)
04-27 14:47:09.610 32314-32314/? W/System.err:     at android.app.ActivityThread.-wrap7(ActivityThread.java)
04-27 14:47:09.610 32314-32314/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
04-27 14:47:09.610 32314-32314/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 14:47:09.610 32314-32314/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-27 14:47:09.610 32314-32314/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6688)
04-27 14:47:09.610 32314-32314/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-27 14:47:09.610 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
04-27 14:47:09.610 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-27 14:47:09.619 32314-32314/? W/System.err: java.lang.SecurityException: getDeviceId: Neither user 10250 nor current process has android.permission.READ_PHONE_STATE.
04-27 14:47:09.620 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1693)
04-27 14:47:09.620 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1646)
04-27 14:47:09.620 32314-32314/? W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:5091)
04-27 14:47:09.620 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:913)
04-27 14:47:09.620 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.j(AdHelper.java:373)
04-27 14:47:09.620 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.b(AdHelper.java:51)
04-27 14:47:09.621 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.a(DianXinSdkUtils.java:86)
04-27 14:47:09.621 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.b(DianXinSdkUtils.java:274)
04-27 14:47:09.621 32314-32314/? W/System.err:     at com.sina.weibo.ScreenOrientationBaseActivity.onStop(ScreenOrientationBaseActivity.java:238)
04-27 14:47:09.621 32314-32314/? W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
04-27 14:47:09.621 32314-32314/? W/System.err:     at com.sina.weibo.bundlemanager.c.a.callActivityOnStop(InstrumentationHook.java:376)
04-27 14:47:09.621 32314-32314/? W/System.err:     at android.app.Activity.performStop(Activity.java:7138)
04-27 14:47:09.621 32314-32314/? W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4596)
04-27 14:47:09.621 32314-32314/? W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4662)
04-27 14:47:09.621 32314-32314/? W/System.err:     at android.app.ActivityThread.-wrap7(ActivityThread.java)
04-27 14:47:09.622 32314-32314/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
04-27 14:47:09.622 32314-32314/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 14:47:09.622 32314-32314/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-27 14:47:09.622 32314-32314/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6688)
04-27 14:47:09.622 32314-32314/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-27 14:47:09.622 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
04-27 14:47:09.622 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-27 14:47:09.625 32314-32314/? W/System.err: java.lang.SecurityException: getSubscriberId: Neither user 10250 nor current process has android.permission.READ_PHONE_STATE.
04-27 14:47:09.625 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1693)
04-27 14:47:09.626 5054-5339/? W/OpenGLRenderer: Incorrectly called buildLayer on View: CellLayoutChildren, destroying layer...
04-27 14:47:09.626 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1646)
04-27 14:47:09.626 32314-32314/? W/System.err:     at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getSubscriberIdForSubscriber(IPhoneSubInfo.java:800)
04-27 14:47:09.626 5054-5339/? W/OpenGLRenderer: Incorrectly called buildLayer on View: CellLayoutChildren, destroying layer...
04-27 14:47:09.626 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2581)
04-27 14:47:09.626 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getSubscriberId(TelephonyManager.java:2562)
04-27 14:47:09.626 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.i(AdHelper.java:348)
04-27 14:47:09.626 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.b(AdHelper.java:51)
04-27 14:47:09.626 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.a(DianXinSdkUtils.java:86)
04-27 14:47:09.626 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.b(DianXinSdkUtils.java:274)
04-27 14:47:09.626 32314-32314/? W/System.err:     at com.sina.weibo.ScreenOrientationBaseActivity.onStop(ScreenOrientationBaseActivity.java:238)
04-27 14:47:09.626 32314-32314/? W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
04-27 14:47:09.626 32314-32314/? W/System.err:     at com.sina.weibo.bundlemanager.c.a.callActivityOnStop(InstrumentationHook.java:376)
04-27 14:47:09.627 32314-32314/? W/System.err:     at android.app.Activity.performStop(Activity.java:7138)
04-27 14:47:09.627 32314-32314/? W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4596)
04-27 14:47:09.627 32314-32314/? W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4662)
04-27 14:47:09.627 32314-32314/? W/System.err:     at android.app.ActivityThread.-wrap7(ActivityThread.java)
04-27 14:47:09.627 32314-32314/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
04-27 14:47:09.627 32314-32314/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 14:47:09.627 32314-32314/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-27 14:47:09.627 32314-32314/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6688)
04-27 14:47:09.627 32314-32314/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-27 14:47:09.627 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
04-27 14:47:09.627 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-27 14:47:09.631 32314-32314/? W/System.err: java.lang.SecurityException: getCellLocation: Neither user 10250 nor current process has android.permission.ACCESS_COARSE_LOCATION.
04-27 14:47:09.631 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1693)
04-27 14:47:09.631 32314-32314/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1646)
04-27 14:47:09.632 32314-32314/? W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getCellLocation(ITelephony.java:3251)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.telephony.TelephonyManager.getCellLocation(TelephonyManager.java:1065)
04-27 14:47:09.632 32314-32314/? W/System.err:     at com.sina.weibo.utils.d.e(AdHelper.java:80)
04-27 14:47:09.632 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.a(DianXinSdkUtils.java:89)
04-27 14:47:09.632 32314-32314/? W/System.err:     at com.sina.weibo.utils.au.b(DianXinSdkUtils.java:274)
04-27 14:47:09.632 32314-32314/? W/System.err:     at com.sina.weibo.ScreenOrientationBaseActivity.onStop(ScreenOrientationBaseActivity.java:238)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1297)
04-27 14:47:09.632 32314-32314/? W/System.err:     at com.sina.weibo.bundlemanager.c.a.callActivityOnStop(InstrumentationHook.java:376)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.app.Activity.performStop(Activity.java:7138)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4596)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4662)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.app.ActivityThread.-wrap7(ActivityThread.java)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1711)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-27 14:47:09.632 32314-32314/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6688)
04-27 14:47:09.632 32314-32314/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-27 14:47:09.632 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
04-27 14:47:09.632 32314-32314/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-27 14:47:09.655 32314-32314/? D/ViewRootImpl@e1c888[SSOAuthorizeActivity]: dispatchDetachedFromWindow
04-27 14:47:09.656 3726-5034/? I/WindowManager: Destroying surface Surface(name=com.sina.weibo/com.sina.weibo.SSOAuthorizeActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2838 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1069 com.android.server.wm.WindowState.removeLocked:1776 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2876 com.android.server.wm.WindowManagerService.removeWindowLocked:2826 com.android.server.wm.WindowManagerService.removeWindowLocked:2641 com.android.server.wm.WindowManagerService.removeWindow:2636 com.android.server.wm.Session.remove:208 
04-27 14:47:09.656 3109-3117/? I/SurfaceFlinger: id=132 Removed TSOAuthoriz (2/4)
04-27 14:47:09.656 3109-3954/? I/SurfaceFlinger: id=132 Removed TSOAuthoriz (-2/4)
04-27 14:47:09.657 3726-5034/? D/LockSettingsStorage: mSKTLockState = 2
04-27 14:47:09.658 3726-5034/? D/InputTransport: Input channel destroyed: fd=436
04-27 14:47:09.658 32314-32314/? D/InputTransport: Input channel destroyed: fd=90
04-27 14:47:09.671 3726-4058/? D/MdnieScenarioControlService:  packageName : com.sec.android.app.launcher    className : com.sec.android.app.launcher.activities.LauncherActivity
04-27 14:47:09.688 32314-3100/? W/System.err: java.lang.SecurityException: getDeviceId: Neither user 10250 nor current process has android.permission.READ_PHONE_STATE.
04-27 14:47:09.688 32314-3100/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1693)
04-27 14:47:09.688 32314-3100/? W/System.err:     at android.os.Parcel.readException(Parcel.java:1646)
04-27 14:47:09.688 32314-3100/? W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:5091)
04-27 14:47:09.688 32314-3100/? W/System.err:     at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:913)
04-27 14:47:09.688 32314-3100/? W/System.err:     at com.sina.weibo.utils.at.b(DeviceInfo.java:205)
04-27 14:47:09.688 32314-3100/? W/System.err:     at com.sina.weibo.requestmodels.gu.createPostRequestBundle(PushSwtichStateParam.java:175)
04-27 14:47:09.688 32314-3100/? W/System.err:     at com.sina.weibo.requestmodels.RequestParam.getNetRequestPostBundle(RequestParam.java:260)
04-27 14:47:09.688 32314-3100/? W/System.err:     at com.sina.weibo.net.f.a(NetEngine.java:4313)
04-27 14:47:09.688 32314-3100/? W/System.err:     at com.sina.weibo.SwitchStateReceiver.a(SwitchStateReceiver.java:167)
04-27 14:47:09.689 32314-3100/? W/System.err:     at com.sina.weibo.SwitchStateReceiver$1.run(SwitchStateReceiver.java:100)
04-27 14:47:09.689 32314-3100/? W/System.err:     at java.lang.Thread.run(Thread.java:762)
```
