### ISSUE TITLE
卸载微博客户端后，第一次分享会crash

### ISSUE THREAD

**Issue by Jungerr** [sinaweibosdk/weibo_android_sdk#264]
java.lang.RuntimeException: Unable to start activity ComponentInfo{tv.danmaku.bili/com.sina.weibo.sdk.share.WbShareTransActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.sina.weibo.sdk.action.ACTION_WEIBO_ACTIVITY pkg=com.sina.weibo (has extras) }
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                               Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.sina.weibo.sdk.action.ACTION_WEIBO_ACTIVITY pkg=com.sina.weibo (has extras) }
                                                                  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                                  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
                                                                  at android.app.Activity.startActivityForResult(Activity.java:3930)
                                                                  at android.app.Activity.startActivityForResult(Activity.java:3890)
                                                                  at com.sina.weibo.sdk.share.WbShareTransActivity.onCreate(WbShareTransActivity.java:64)
                                                                  at android.app.Activity.performCreate(Activity.java:6251)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by zhimeiyue** [comment]
我的也会这样，请问找到原因没有？？
