### ISSUE TITLE
aar在64在m3 note上崩溃

### ISSUE THREAD

**Issue by MrHangVIP** [sinaweibosdk/weibo_android_sdk#281]
当前应用程序版本：0.0.5-->1
手机设备信息：m3 note
手机系统版本：5.1
崩溃时间：2017-05-24 14:49:29
崩溃日志：
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.hoge.android.app.hljapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hoge.android.app.hljapp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libweibosdkcore.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:988)
	at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:43)
	at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:400)
	at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
	at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:232)
	at java.lang.Thread.run(Thread.java:818)

**Comment by MrHangVIP** [comment]
可以直接添加64位so在自己项目中
