### ISSUE TITLE
APP通过系统ota升级后，创建微博分享接口实例的时候WeiboAppManager报错，造成anr

### ISSUE THREAD

**Issue by xfnbing** [sinaweibosdk/weibo_android_sdk#301]
at android.os.BinderProxy.transactNative(Native method)
  at android.os.BinderProxy.transact(Binder.java:615)
  at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4262)
  at android.app.ActivityThread.acquireProvider(ActivityThread.java:5516)
  at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2282)
  at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1608)
  at android.content.ContentResolver.query(ContentResolver.java:550)
  at android.content.ContentResolver.query(ContentResolver.java:485)
  at com.sina.weibo.sdk.WeiboAppManager.queryWeiboInfoByProvider(WeiboAppManager.java:124)
  at com.sina.weibo.sdk.WeiboAppManager.queryWeiboInfoInternal(WeiboAppManager.java:91)
  at com.sina.weibo.sdk.WeiboAppManager.getWeiboInfo(WeiboAppManager.java:87)
  - locked <0x0698c288> (a com.sina.weibo.sdk.WeiboAppManager)
  at com.sina.weibo.sdk.api.share.WeiboShareAPIImpl.<init>(WeiboShareAPIImpl.java:94)
  at com.sina.weibo.sdk.api.share.WeiboShareSDK.createWeiboAPI(WeiboShareSDK.java:39)
  at com.sina.weibo.sdk.api.share.WeiboShareSDK.createWeiboAPI(WeiboShareSDK.java:52)

**Comment by sinaweibosdk** [comment]
尝试升级最新的weibo sdk
