### ISSUE TITLE
用android studio 编译出现 com.android.dex.DexException: Multiple dex files define Lcom/sina/weibo/sdk/BuildConfig;错误

### ISSUE THREAD

**Issue by shirensong** [sinaweibosdk/weibo_android_sdk#32]
Error:Execution failed for task ':app:dexDebug'.
Error Code:
    2
Output:
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/sina/weibo/sdk/BuildConfig;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
        at com.android.dx.command.dexer.Main.run(Main.java:230)
        at com.android.dx.command.dexer.Main.main(Main.java:199)
        at com.android.dx.command.Main.main(Main.java:103)

**Comment by gengjiawen** [comment]
@stackia it works, thank you.

**Comment by RockyLin** [comment]
正解：stackia commented on Nov 20, 2014
解决方法：解包 weibosdkcore.jar，删除里面的 BuildConfig.class，重新打包 jar。
本来这个文件不应该存在于jar里，不知微博的开发怎么搞进去的。

（不要用mac自带的解压和压缩）

**Comment by comk** [comment]
/**
正解：stackia commented on Nov 20, 2014
解决方法：解包 weibosdkcore.jar，删除里面的 BuildConfig.class，重新打包 jar。
本来这个文件不应该存在于jar里，不知微博的开发怎么搞进去的。
**/

删除方法：直接用winrar打开然后选中BuildConfig.class文件 ，再点击工具栏的“删除”图标就可以了。

**Comment by yongjhih** [comment]
See also: https://github.com/8tory/weibo-android-sdk

**Comment by gengjiawen** [comment]
@yongjhih do you work in sina?I see your repository is forked.

**Comment by yongjhih** [comment]
No.We just restructed repository for easy to use.

**Comment by gengjiawen** [comment]
@sinaweibosdk why close this ?
