### ISSUE TITLE
新浪微博SDK-4.1.0版本崩溃，请解决，多谢了。

### ISSUE THREAD

**Issue by BlackMagicHappy** [sinaweibosdk/weibo_android_sdk#320]
你好，我们项目组使用了新浪微博的SDK Android版本， 目前遇到一个崩溃如下：

09-11 08:58:08.404 16844-16844/***************** E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: *****************, PID: 16844
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{*****************/com.sina.weibo.sdk.share.WbShareTransActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                        at android.os.Looper.loop(Looper.java:156)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
                                                                        at com.sina.weibo.sdk.api.WeiboMultiMessage.toObject(WeiboMultiMessage.java:99)
                                                                        at com.sina.weibo.sdk.share.WbShareTransActivity.checkSource(WbShareTransActivity.java:68)
                                                                        at com.sina.weibo.sdk.share.WbShareTransActivity.onCreate(WbShareTransActivity.java:62)
                                                                        at android.app.Activity.performCreate(Activity.java:6910)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                        at android.os.Looper.loop(Looper.java:156) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831) 

请修复，多谢了。

**Comment by BlackMagicHappy** [comment]
补充，是测试使用一款叫做IntentSuit的软件进行测试发现的。

**Comment by BlackMagicHappy** [comment]
补充，采用命令拉起也是会崩溃的：
adb shell am start -n {APK包名}/com.sina.weibo.sdk.share.WbShareTransActivity

**Comment by anxinxu** [comment]
真的加个判空可以嘛。。求求你们了

**Comment by coolegos** [comment]
`export=false` 手动修改。😢
