### ISSUE TITLE
微博分享与阿里推送一起用，使android7.0手机崩溃

### ISSUE THREAD

**Issue by yueshiwei** [sinaweibosdk/weibo_android_sdk#333]
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libweibosdkcore.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                       at java.lang.System.loadLibrary(System.java:1562)
                                                       at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:42)
                                                       at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:62)
                                                       at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:400)
                                                       at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
                                                       at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:232)
                                                       at java.lang.Thread.run(Thread.java:761)

**Comment by ElegantDancer** [comment]
我这边在适配8.0的时候，也出现了类似的崩溃信息，使用的是 2.0.3的aar。
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libweibosdkcore.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
at java.lang.System.loadLibrary(System.java:1660)
at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:43)
at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:63)
at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:400)
at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)

**Comment by wudkj** [comment]
我也遇到了这个问题,官方没有任何回复,我的解决方法是:
在main目录下新建jniLibs(有就不要建了)
然后将下载的weibo github 包解压后得到的so目录下的所有文件夹和文件都复制进去
