### ISSUE TITLE
WbShareTransActivity报出class name is null

### ISSUE THREAD

**Issue by Taonce** [sinaweibosdk/weibo_android_sdk#356]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aulton.aee/com.sina.weibo.sdk.share.WbShareTransActivity}: java.lang.NullPointerException: class name is null
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: class name is null
at android.content.ComponentName.(ComponentName.java:114)
at android.content.Intent.setClassName(Intent.java:7100)
at com.sina.weibo.sdk.share.WbShareTransActivity.onCreate(Native Method)
at android.app.Activity.performCreate(Activity.java:6288)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
... 9 more

**Comment by zjc** [comment]
遇到同样的错误信息

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.soqu.client/com.sina.weibo.sdk.share.WbShareTransActivity}: java.lang.NullPointerException: class name is null
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
3 ......
4 Caused by:
5 java.lang.NullPointerException:class name is null
6 android.content.ComponentName.<init>(ComponentName.java:114)
7 android.content.Intent.setClassName(Intent.java:7100)
8 com.sina.weibo.sdk.share.WbShareTransActivity.onCreate(Unknown Source)
9 android.app.Activity.performCreate(Activity.java:6288)
10 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
12 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
13 android.app.ActivityThread.-wrap11(ActivityThread.java)
14 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
15 android.os.Handler.dispatchMessage(Handler.java:104)
16 android.os.Looper.loop(Looper.java:148)
17 android.app.ActivityThread.main(ActivityThread.java:5417)
18 java.lang.reflect.Method.invoke(Native Method)
19 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
20 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by wenwenwen888** [comment]
+1
java.lang.NullPointerException: class name is null
at android.content.ComponentName.(ComponentName.java:114)
at android.content.Intent.setClassName(Intent.java:7100)
at com.sina.weibo.sdk.share.WbShareTransActivity.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:6288)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at com.qiyukf.unicorn.h.a.callActivityOnCreate(Unknown Source)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
