### ISSUE TITLE
微博登录或直播，报错：couldn't find "libweibosdkcore.so"

### ISSUE THREAD

**Issue by DuanBinbin** [sinaweibosdk/weibo_android_sdk#357]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.pi.pilot.live-2/base.apk"],nativeLibraryDirectories=[/data/app/com.pi.pilot.live-2/lib/arm64, /data/app/com.pi.pilot.live-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libweibosdkcore.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
	at java.lang.System.loadLibrary(System.java:1533)
	at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:42)
	at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:62)
	at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:400)
	at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
	at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:232)
	at java.lang.Thread.run(Thread.java:776)

**Comment by DuanBinbin** [comment]
目前我的解决方案是在app -> scr -> main下，新建“jniLibs”文件夹，将weibo_android_sdk -> so 下的文件直接拷贝过去。

**Comment by fgb3420** [comment]
还好我翻了一下issue，帮大忙了兄弟

**Comment by imononoke** [comment]
4.2.7的aar里只包含了armeabi, armeabi-v7a和x86这三个平台的so文件，其它平台的设备运行起来就会报找不到weibosdkcore.so的错了。。需要添加其它平台的so文件。。
