### ISSUE TITLE
BUG NullPointerException

### ISSUE THREAD

**Issue by Pinick** [sinaweibosdk/weibo_android_sdk#358]
java.lang.RuntimeException: Unable to resume activity {com.songheng.mopnovel/com.songheng.novel.thirdlogin.view.WBAuthActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=32973, result=-1, data=Intent { cmp=com.sina.weibog3/com.sina.weibo.SSOActivity (has extras) }} to activity {com.songheng.mopnovel/com.songheng.novel.thirdlogin.view.WBAuthActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2932)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2961)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
	at android.app.ActivityThread.access$800(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1243)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5426)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=32973, result=-1, data=Intent { cmp=com.sina.weibog3/com.sina.weibo.SSOActivity (has extras) }} to activity {com.songheng.mopnovel/com.songheng.novel.thirdlogin.view.WBAuthActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3519)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2919)
	... 12 more
Caused by: java.lang.NullPointerException
	at com.sina.weibo.sdk.auth.BaseSsoHandler.authorizeCallBack(BaseSsoHandler.java:227)
	at com.songheng.novel.thirdlogin.view.WBAuthActivity.onActivityResult(WBAuthActivity.java:168)
	at android.app.Activity.dispatchActivityResult(Activity.java:5493)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3515)
java.lang.NullPointerException
	at com.sina.weibo.sdk.auth.BaseSsoHandler.authorizeCallBack(BaseSsoHandler.java:227)
	at com.songheng.novel.thirdlogin.view.WBAuthActivity.onActivityResult(WBAuthActivity.java:168)
	at android.app.Activity.dispatchActivityResult(Activity.java:5493)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3515)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2919)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2961)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
	at android.app.ActivityThread.access$800(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1243)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5426)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Tiger3590** [comment]
t

**Comment by Pinick** [comment]
麻蛋怎么没人回复?微博越来越垃圾了
