### ISSUE TITLE
空指针crash：java.io.InputStream.read 

### ISSUE THREAD

**Issue by leo-plus** [sinaweibosdk/weibo_android_sdk#373]
复现步骤不明确，大概为APP启动后进入主页后。
以下为crash栈：
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
	at com.sina.weibo.sdk.net.HttpManager.java.lang.String readConnectResponse(java.net.HttpURLConnection,boolean)(SourceFile:)
	at com.sina.weibo.sdk.net.HttpManager.java.lang.String requestHttpExecute(android.content.Context,java.lang.String,java.lang.String,com.sina.weibo.sdk.net.WeiboParameters)(SourceFile:)
	at com.sina.weibo.sdk.net.HttpManager.java.lang.String openUrl(android.content.Context,java.lang.String,java.lang.String,com.sina.weibo.sdk.net.WeiboParameters)(SourceFile:)
	at com.sina.weibo.sdk.utils.AidTask.java.lang.String loadAidFromNet()(SourceFile:)
	at com.sina.weibo.sdk.utils.AidTask.access$200(SourceFile:)
	at com.sina.weibo.sdk.utils.AidTask$2.void run()(SourceFile:)
	at java.lang.Thread.run(Thread.java:)

**Comment by Mozziehh** [comment]
java.lang.NullPointerException
Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
com.sina.weibo.sdk.net.HttpManager.a(HttpManager.java:141)

嗯，我这里也有一个 ，麻烦速度解决

**Comment by weidongjian** [comment]
++++++++++++++++++++++++++++++++++++++++
readConnectResponse
f34c2075299eaa1aae486d36018fcf9f
++++++++++++++++++++++++++++++++++++++++
-----------------------Crash 1 Message-----------------------
完整log: logcat.txt
06-28 04:19:22.976 E/AndroidRuntime( 9830): FATAL EXCEPTION: Thread-423
06-28 04:19:22.976 E/AndroidRuntime( 9830): Process: com.mt.mtxx.mtxx, PID: 9830
06-28 04:19:22.976 E/AndroidRuntime( 9830): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
06-28 04:19:22.976 E/AndroidRuntime( 9830): 	at com.sina.weibo.sdk.net.HttpManager.readConnectResponse(HttpManager.java:141)
06-28 04:19:22.976 E/AndroidRuntime( 9830): 	at com.sina.weibo.sdk.net.HttpManager.requestHttpExecute(HttpManager.java:104)
06-28 04:19:22.976 E/AndroidRuntime( 9830): 	at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:62)
06-28 04:19:22.976 E/AndroidRuntime( 9830): 	at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:403)
06-28 04:19:22.976 E/AndroidRuntime( 9830): 	at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
06-28 04:19:22.976 E/AndroidRuntime( 9830): 	at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:235)
06-28 04:19:22.976 E/AndroidRuntime( 9830): 	at java.lang.Thread.run(Thread.java:760)

-----------------------Process has died-----------------------

我这边也是出现了几次这样的问题，麻烦排查下

**Comment by super-hu** [comment]
+1

` java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
        at com.sina.weibo.sdk.net.HttpManager.readConnectResponse(Unknown Source:21)
        at com.sina.weibo.sdk.net.HttpManager.requestHttpExecute(Unknown Source:123)
        at com.sina.weibo.sdk.net.HttpManager.openUrl(Unknown Source:0)
        at com.sina.weibo.sdk.net.AsyncWeiboRunner$RequestRunner.doInBackground(Unknown Source:8)
        at com.sina.weibo.sdk.net.AsyncWeiboRunner$RequestRunner.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) `

**Comment by coolegos** [comment]
使用的什么版本的呢

**Comment by leo-plus** [comment]
版本记不得了，下次一定提供版本号。

**Comment by jianweizhou** [comment]
com.sina.weibo.sdk:core:4.2.5 调起微博登陆时发生crash.
01-09 03:35:06.258 E/AndroidRuntime(24201): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.net.HttpManager.readConnectResponse(HttpManager.java:141)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.net.HttpManager.requestHttpExecute(HttpManager.java:104)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:62)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:403)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:235)
01-09 03:35:06.258 E/AndroidRuntime(24201): at java.lang.Thread.run(Thread.java:760)

**Comment by jianweizhou** [comment]
com.sina.weibo.sdk:core:4.3.0 验证已修复
