### ISSUE TITLE
UnsatisfiedLinkError libweibosdkcore is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by fengqingxiuyi** [sinaweibosdk/weibo_android_sdk#378]
`UncaughtException detected: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/cn.atmobi.mamhao-2/lib/arm/libweibosdkcore.so" is 64-bit instead of 32-bit
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:42)
        at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:62)
        at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:403)
        at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
        at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:235)
        at java.lang.Thread.run(Thread.java:818)`

很奇怪，在自己创建的Project中没有问题，但是将library移植到公司的Project中会报错

**Comment by fengqingxiuyi** [comment]
我将公司Project支持的SO库架构从
`ndk {
            abiFilters "armeabi"
        }`
改为
`ndk {
            abiFilters "armeabi", "armeabi-v7a"
        }`
就没有问题了，但是我将自己的Project支持的SO库架构改为
`ndk {
            abiFilters "armeabi"
        }`并没有出现问题。
尚不清楚根本原因，如果增加armeabi-v7同时也会增加APK的大小，所以再看一下

**Comment by fengqingxiuyi** [comment]
看日志是分包找不到正确的so库的问题
