### ISSUE TITLE
登陆返回信息解析出错

### ISSUE THREAD

**Issue by mrichie** [sinaweibosdk/weibo_android_sdk#39]
```

11-16 11:10:45.932: W/SchedulingPolicyService(239): end to sps->requestPriority()
11-16 11:10:45.962: E/QCALOG(525): [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
11-16 11:10:45.992: W/System.err(9953): java.lang.reflect.InvocationTargetException
11-16 11:10:45.992: W/System.err(9953):      at java.lang.reflect.Method.invokeNative(Native Method)
11-16 11:10:45.992: W/System.err(9953):      at java.lang.reflect.Method.invoke(Method.java:515)
11-16 11:10:45.992: W/System.err(9953):      at com.sina.weibo.models.gson.GsonHelper.fromJson(GsonHelper.java:181)
11-16 11:10:45.992: W/System.err(9953):      at com.sina.weibo.models.gson.GsonUtils.fromJson(GsonUtils.java:29)
11-16 11:10:45.992: W/System.err(9953):      at com.sina.weibo.utils.s.ab(Utils.java:6449)
11-16 11:10:45.992: W/System.err(9953):      at com.sina.weibo.net.f.a(NetEngine.java:183)
11-16 11:10:45.992: W/System.err(9953):      at com.sina.weibo.business.az.b(LoginCenter.java:57)
11-16 11:10:45.992: W/System.err(9953):      at com.sina.weibo.d.a.a(Controller.java:737)
11-16 11:10:45.992: W/System.err(9953):      at com.sina.weibo.SSOAuthorizeActivity$b.a(SSOAuthorizeActivity.java:140)
11-16 11:10:45.992: W/System.err(9953):      at com.sina.weibo.SSOAuthorizeActivity$b.doInBackground(SSOAuthorizeActivity.java:118)
11-16 11:10:45.992: W/System.err(9953):      at android.os.AsyncTask$2.call(AsyncTask.java:288)
11-16 11:10:46.002: W/System.err(9953):      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-16 11:10:46.002: W/System.err(9953):      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
11-16 11:10:46.002: W/System.err(9953):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-16 11:10:46.002: W/System.err(9953):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-16 11:10:46.002: W/System.err(9953):      at java.lang.Thread.run(Thread.java:841)
11-16 11:10:46.002: W/System.err(9953): Caused by: com.sina.weibo.gson.JsonParseException: End of input at line 1 column 1
11-16 11:10:46.002: W/System.err(9953):      at com.sina.weibo.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1426)
11-16 11:10:46.002: W/System.err(9953):      at com.sina.weibo.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1563)
11-16 11:10:46.002: W/System.err(9953):      at com.sina.weibo.gson.stream.JsonReader.doPeek(JsonReader.java:528)
11-16 11:10:46.002: W/System.err(9953):      at com.sina.weibo.gson.stream.JsonReader.peek(JsonReader.java:419)
11-16 11:10:46.002: W/System.err(9953):      at com.sina.weibo.gson.Gson.fromJson(Gson.java:800)
11-16 11:10:46.002: W/System.err(9953):      at com.sina.weibo.gson.Gson.fromJson(Gson.java:769)
11-16 11:10:46.002: W/System.err(9953):      at com.sina.weibo.gson.Gson.fromJson(Gson.java:718)
11-16 11:10:46.002: W/System.err(9953):      at com.sina.weibo.gson.Gson.fromJson(Gson.java:690)
11-16 11:10:46.002: W/System.err(9953):      ... 16 more
```

之前是能登陆成功的，最近才出现过这个错误，貌似是登陆返回的信息库解析出错了，我看ios sdk那边已经升级到2.5.1, android sdk 2.5.0是不是没有用最新版sdk的问题

**Comment by cong2014** [comment]
是不是 proguard 搞得
