### ISSUE TITLE
在网络代理，Android手机未安装微博APP的前提下，打开分享，微博分享，快速返回第三方应用，重复几遍，系统奔溃

### ISSUE THREAD

**Issue by newbee123456** [sinaweibosdk/weibo_android_sdk#399]
在网络代理，Android手机未安装微博APP的前提下，打开分享，微博分享，快速返回第三方应用，重复几遍，系统奔溃；
崩溃日志：
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@1d4ae7f is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
	at android.app.Dialog.show(Dialog.java:330)
	at com.sina.weibo.sdk.web.WeiboSdkWebActivity.onReceivedSslErrorCallBack(WeiboSdkWebActivity.java:376)
	at com.sina.weibo.sdk.web.client.BaseWebViewClient.onReceivedSslError(BaseWebViewClient.java:48)
	at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedSslError(WebViewContentsClientAdapter.java:526)
	at org.chromium.android_webview.AwContentsClientBridge$$Lambda$1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:171)
	at android.app.ActivityThread.main(ActivityThread.java:6699)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
看日志原因应该是调用WeiboSdkWebActivity中onReceivedSslErrorCallBack方法的时候，创建dialog对应的activity被销毁了，麻烦对这个崩溃问题做下优化，修复一下

**Comment by coolegos** [comment]
@sinaweibosdk 这个问题修复了吗？看4.4.1 还有bug 呢
