### ISSUE TITLE
空指针crash：java.io.InputStream.read

### ISSUE THREAD

**Issue by jianweizhou** [sinaweibosdk/weibo_android_sdk#435]
com.sina.weibo.sdk:core:4.2.5  调起微博登陆时发生crash.

01-09 03:35:06.258 E/AndroidRuntime(24201): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.net.HttpManager.readConnectResponse(HttpManager.java:141)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.net.HttpManager.requestHttpExecute(HttpManager.java:104)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:62)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:403)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
01-09 03:35:06.258 E/AndroidRuntime(24201): at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:235)
01-09 03:35:06.258 E/AndroidRuntime(24201): at java.lang.Thread.run(Thread.java:760)

**Comment by jianweizhou** [comment]
com.sina.weibo.sdk:core:4.3.0 验证已修复
