### ISSUE TITLE
导入AndroidStudio，运行时加载不了weibosdkcore

### ISSUE THREAD

**Issue by firebear** [sinaweibosdk/weibo_android_sdk#45]
我是先把weiboSDK的包名从com.sina.weibo.sdk改为com.sina.weibo.sdklib，然后导入到我的Android Studio项目中，成为一个module。weibosdkcore.jar在weiboSDK的lib目录下。dependencies设置看起来都正确，编译通过，安装成功，但是一运行，调用sdk时，闪退。
以下是exception。大家有碰到这个问题的吗，你们是怎么解决的。多谢指点！
2-25 09:46:56.818      520-955/? I/ActivityManager﹕ START {cmp=com.sina.weibo/.SSOActivity (has extras) u=0} from pid 20193
12-25 09:46:56.818  20193-20288/com.momomobile.goer E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-25267
    java.lang.ExceptionInInitializerError
            at com.sina.weibo.sdk.net.AsyncWeiboRunner.request(AsyncWeiboRunner.java:84)
            at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:307)
            at com.sina.weibo.sdk.utils.AidTask.access$2(AidTask.java:294)
            at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:159)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.UnsatisfiedLinkError: Couldn't load weibosdkcore: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:365)
            at java.lang.System.loadLibrary(System.java:535)
            at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:83)
            at com.sina.weibo.sdk.net.AsyncWeiboRunner.request(AsyncWeiboRunner.java:84)
            at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:307)
            at com.sina.weibo.sdk.utils.AidTask.access$2(AidTask.java:294)
            at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:159)
            at java.lang.Thread.run(Thread.java:856)

**Comment by ratdream** [comment]
你好，我把so都放到src/main/jniLibs都拷贝到对应的目录下了，仍然报这个错，想问一下还有啥需要注意的地方么

**Comment by pkliang** [comment]
记得在jniLibs下要新建一个armeabi-v7a文件夹，并放入.so文件

**Comment by firebear** [comment]
贴个我的jniLibs目录结构出来，weibo的.so都高亮了。
我跳过的坑，不一定是你碰到的坑。
仅供参考。

![image](https://cloud.githubusercontent.com/assets/718573/6599672/168c5c8e-c846-11e4-8f85-bd9f9b3103bd.png)

**Comment by tarlaw** [comment]
找了半天，绕了不少弯路，感谢！

**Comment by yongjhih** [comment]
See also: https://github.com/8tory/weibo-android-sdk
