### ISSUE TITLE
4.3.8 sdk crash

### ISSUE THREAD

**Issue by xyz-fly** [sinaweibosdk/weibo_android_sdk#450]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", couldn't find "libwind.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at com.weibo.ssosdk.WeiboSsoSdk.<clinit>(SourceFile:24)
        at com.weibo.ssosdk.WeiboSsoSdk.a(Unknown Source:0)
        at com.sina.weibo.sdk.sso.WeiboSsoManager.init(SourceFile:36)
        at com.sina.weibo.sdk.WbSdk.install(SourceFile:33)

**Comment by wuhh2016** [comment]
也遇到这个问题，微博版本9.3.3

**Comment by sinaweibosdk** [comment]
加我QQ 879073159 我帮你解决

**Comment by gaobq** [comment]
> 加我QQ 879073159 我帮你解决

我也遇到此问题, 为什么QQ号搜索不到?

**Comment by hamberluo** [comment]
> > 加我QQ 879073159 我帮你解决
> 
> 我也遇到此问题, 为什么QQ号搜索不到?

我也搜不到

**Comment by sqken** [comment]
> 加我QQ 879073159 我帮你解决
加了，没给我通过验证。

**Comment by sinaweibosdk** [comment]
QQ号错误导致，请联系879073159
