### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by CXinQuan** [sinaweibosdk/weibo_android_sdk#473]
java.lang.Exception: visitor login failed
        at com.weibo.ssosdk.WeiboSsoSdk.getAid(WeiboSsoSdk.java:363)
        at com.sina.weibo.sdk.sso.WeiboSsoManager.initAid(WeiboSsoManager.java:43)
        at com.sina.weibo.sdk.sso.WeiboSsoManager.init(WeiboSsoManager.java:38)
        at com.sina.weibo.sdk.WbSdk.install(WbSdk.java:33)

**Comment by YouCii** [comment]
同问, authorize不成功
