### ISSUE TITLE
SSOAuthorizeActivity 被finish掉

### ISSUE THREAD

**Issue by jyfree** [sinaweibosdk/weibo_android_sdk#480]
07-17 19:04:59.552 7515-7515/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sina.weibo, PID: 7515
    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.sina.weibo.models.User)
        at android.os.Parcel.writeSerializable(Parcel.java:1407)
        at android.os.Parcel.writeValue(Parcel.java:1354)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:657)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
        at android.os.Bundle.writeToParcel(Bundle.java:1034)
        at android.os.Parcel.writeBundle(Parcel.java:682)
        at android.content.Intent.writeToParcel(Intent.java:7692)
        at android.app.ActivityManagerProxy.finishActivity(ActivityManagerNative.java:2803)
        at android.app.Activity.finish(Activity.java:4803)
        at android.app.Activity.finish(Activity.java:4821)
        at com.sina.weibo.BaseActivity.forceFinish(BaseActivity.java:1778)
        at com.sina.weibo.SSOAuthorizeActivity.finish(SSOAuthorizeActivity.java:873)
        at com.sina.weibo.SSOAuthorizeActivity$b.a(SSOAuthorizeActivity.java:286)
        at com.sina.weibo.SSOAuthorizeActivity$b.onPostExecute(SSOAuthorizeActivity.java:148)
        at com.sina.weibo.ae.d.finish(ExtendedAsyncTask.java:335)
        at com.sina.weibo.ae.d.access$000(ExtendedAsyncTask.java:25)
        at com.sina.weibo.ae.d$1.handleMessage(ExtendedAsyncTask.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:5671)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
     Caused by: java.io.NotSerializableException: org.json.JSONObject
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)

**Comment by sinaweibosdk** [comment]
微博客户端最新版本已经修复该问题。
