### ISSUE TITLE
微博分享时，只要带上图片，就无法打开分享页（只有文字分享正常）最新版4.41

### ISSUE THREAD

**Issue by xiaxveliang** [sinaweibosdk/weibo_android_sdk#486]
用git上的weibosdkdemo测试（将key、包名、签名替换为我们自己的App配置）
java.lang.Exception: visitor login failed
at com.weibo.ssosdk.WeiboSsoSdk.getAid(WeiboSsoSdk.java:363)
at com.sina.weibo.sdk.sso.WeiboSsoManager.initAid(WeiboSsoManager.java:42)
at com.sina.weibo.sdk.sso.WeiboSsoManager.init(WeiboSsoManager.java:37)
at com.sina.weibo.sdk.sso.WeiboSsoManager.getAid(WeiboSsoManager.java:55)
at com.sina.weibo.sdk.network.intercept.CommonParamInterception.doIntercept(CommonParamInterception.java:34)
at com.sina.weibo.sdk.network.impl.FixRequestTask.run(FixRequestTask.java:53)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

**Comment by sinaweibosdk** [comment]
需要找我报备下（879073159）

**Comment by downtail** [comment]
遇到这个问题，改如何解决

**Comment by xiaxveliang** [comment]
不同的情况，解决方式不一样吧。

我这是这样解决的：找微博相关同事加白名单后解决。

**Comment by downtail** [comment]
好的，想了下不发图了。。

**Comment by ZiqiangGe** [comment]
遇到这个问题了 怎么解决啊

**Comment by xiaxveliang** [comment]
> 遇到这个问题了 怎么解决啊

不同的情况，解决方式不一样吧。
我这是这样解决的：找微博相关同事加白名单后解决。

**Comment by lefan14** [comment]
> 需要找我报备下（879073159）

请问我们使用google server 之后 在WbSdk.install之后出现该错误
java.lang.Exception: visitor login failed
at com.weibo.ssosdk.WeiboSsoSdk.getAid(WeiboSsoSdk.java:363)
at com.sina.weibo.sdk.sso.WeiboSsoManager.initAid(WeiboSsoManager.java:42)
at com.sina.weibo.sdk.sso.WeiboSsoManager.init(WeiboSsoManager.java:37)
at com.sina.weibo.sdk.WbSdk.install(WbSdk.java:33)

**Comment by henryneu** [comment]
同问，已安装微博客户端的情况下，分享都正常，没有安装微博客户端的时候，走微博网页分享，不带图片就正常，只要带图片就会报这个错误，然后分享失败！
