### ISSUE TITLE
已经添加了 READ_PHONE_STATE ，还是报错误

### ISSUE THREAD

**Issue by weifans** [sinaweibosdk/weibo_android_sdk#491]
`W/System.err: java.lang.SecurityException: getSerial requires READ_PHONE_STATE or READ_PRIVILEGED_PHONE_STATE permission
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
W/System.err:     at android.os.Parcel.readException(Parcel.java:1871)
        at android.os.IDeviceIdentifiersPolicyService$Stub$Proxy.getSerial(IDeviceIdentifiersPolicyService.java:86)
        at android.os.Build.getSerial(Build.java:135)
        at com.weibo.ssosdk.MfpBuilder.getSerialNoForO(MfpBuilder.java:532)
        at com.weibo.ssosdk.MfpBuilder.getSerialNo(MfpBuilder.java:496)
        at com.weibo.ssosdk.MfpBuilder.genMfpString(MfpBuilder.java:251)
        at com.weibo.ssosdk.MfpBuilder.getMfp(MfpBuilder.java:186)
        at com.weibo.ssosdk.WeiboSsoSdk.updateInfo(WeiboSsoSdk.java:273)
        at com.weibo.ssosdk.WeiboSsoSdk.access$200(WeiboSsoSdk.java:22)
        at com.weibo.ssosdk.WeiboSsoSdk$2.run(WeiboSsoSdk.java:97)
        at java.lang.Thread.run(Thread.java:764)
W/System.err: Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerial(DeviceIdentifiersPolicyService.java:64)
        at android.os.IDeviceIdentifiersPolicyService$Stub.onTransact(IDeviceIdentifiersPolicyService.java:52)
        at android.os.Binder.execTransact(Binder.java:733)
`

**Comment by sahabe1** [comment]
@weifans have you fixed this issues?

**Comment by cijianzy** [comment]
@sinaweibosdk 怎么就关了？
