### ISSUE TITLE
使用4.4.1的微博sdk，会有如下的错误。facebook版本4.26.0，同时升级facebook版本能够解决。 请问是否是sdk里面有facebook的调用？ 

### ISSUE THREAD

**Issue by yeliang2019** [sinaweibosdk/weibo_android_sdk#496]
使用4.4.1的微博sdk，会有如下的错误。facebook版本4.26.0，同时升级facebook版本能够解决。
请问是否是sdk里面有facebook的调用？ 
Caused by: java.lang.ClassNotFoundException: Didn't find class "bolts.AppLinks" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.sogou.passportsdk.demo-0FmQTf0hoWNNrdyGkXSstA==/base.apk"],nativeLibraryDirectories=[/data/app/com.sogou.passportsdk.demo-0FmQTf0hoWNNrdyGkXSstA==/lib/arm64, /data/app/com.sogou.passportsdk.demo-0FmQTf0hoWNNrdyGkXSstA==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.appevents.internal.SourceApplicationInfo$Factory.create(SourceApplicationInfo.java:132)?
        at com.facebook.appevents.internal.ActivityLifecycleTracker.onActivityCreated(ActivityLifecycleTracker.java:120)?
        at com.facebook.appevents.internal.ActivityLifecycleTracker$1.onActivityCreated(ActivityLifecycleTracker.java:73)?
        at android.app.Application.dispatchActivityCreated(Application.java:232)?

**Comment by sinaweibosdk** [comment]
不是，SDK里面没有facebook
