### ISSUE TITLE
初始化崩溃

### ISSUE THREAD

**Issue by maiyong** [sinaweibosdk/weibo_android_sdk#498]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.weibo.ssosdk.WeiboSsoSdk$VisitorLoginInfo.getAid()' on a null object reference
        at com.sina.weibo.sdk.sso.WeiboSsoManager$1.handler(WeiboSsoManager.java:46)
        at com.weibo.ssosdk.WeiboSsoSdk$5.run(WeiboSsoSdk.java:351)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

我调用install时出现崩溃了，请问下是什么原因

**Comment by maiyong** [comment]
sdk在调用native接口时说参数错误，具体哪个参数也没说，我要怎么排查？

**Comment by maiyong** [comment]
4.4.2的sdk会崩溃，我用4.4.1的没事了

**Comment by xyz-fly** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.weibo.ssosdk.WeiboSsoSdk$a.a()' on a null object reference

**Comment by xyz-fly** [comment]
也遇到这个问题了

**Comment by xymelon** [comment]
同遇见。。。这么大问题 没人管？

**Comment by JasonNorris** [comment]
相同的问题，调用WbSdk.install()就会报错
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.weibo.ssosdk.WeiboSsoSdk$VisitorLoginInfo.getAid()' on a null object reference

**Comment by sinaweibosdk** [comment]
最新版本已经修复。
