### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by qluan** [sinaweibosdk/weibo_android_sdk#50]
Umeng统计到的crash
机型：三星GT-S6818（4.1.2）、vivo S3+（4.2.2）
log如下：
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.douban.frodo/com.sina.weibo.sdk.component.WeiboSdkBrowser}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2118)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2143)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4952)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at android.content.res.AssetManager.openAsset(Native Method)
    at android.content.res.AssetManager.open(AssetManager.java:315)
    at android.content.res.AssetManager.open(AssetManager.java:289)
    at com.sina.weibo.sdk.utils.ResourceManager.getDrawableFromAssert(ResourceManager.java:191)
    at com.sina.weibo.sdk.utils.ResourceManager.getNinePatchDrawable(ResourceManager.java:111)
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.setContentView(WeiboSdkBrowser.java:259)
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:127)
    at android.app.Activity.performCreate(Activity.java:5188)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2082)
    ... 11 more
java.lang.NullPointerException
    at android.content.res.AssetManager.openAsset(Native Method)
    at android.content.res.AssetManager.open(AssetManager.java:315)
    at android.content.res.AssetManager.open(AssetManager.java:289)
    at com.sina.weibo.sdk.utils.ResourceManager.getDrawableFromAssert(ResourceManager.java:191)
    at com.sina.weibo.sdk.utils.ResourceManager.getNinePatchDrawable(ResourceManager.java:111)
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.setContentView(WeiboSdkBrowser.java:259)
    at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:127)
    at android.app.Activity.performCreate(Activity.java:5188)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2082)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2143)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4952)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by sinaweibosdk** [comment]
已修复此问题，可以下载新的sdk试试

**Comment by xmstudio** [comment]
Device Model: Samsung SM-N910P

Stack trace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.newsand.duobao/com.sina.weibo.sdk.component.WeiboSdkBrowser}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2540)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2599)
	at android.app.ActivityThread.access$900(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5748)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.sina.weibo.sdk.utils.ResourceManager.getDrawableFromAssert(ResourceManager.java:209)
	at com.sina.weibo.sdk.utils.ResourceManager.getNinePatchDrawable(ResourceManager.java:114)
	at com.sina.weibo.sdk.component.WeiboSdkBrowser.initTitleBar(WeiboSdkBrowser.java:377)
	at com.sina.weibo.sdk.component.WeiboSdkBrowser.setContentView(WeiboSdkBrowser.java:273)
	at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:131)
	at android.app.Activity.performCreate(Activity.java:5600)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2504)
	... 11 more
java.lang.NullPointerException
	at android.content.res.AssetManager.openAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:316)
	at android.content.res.AssetManager.open(AssetManager.java:290)
	at com.sina.weibo.sdk.utils.ResourceManager.getDrawableFromAssert(ResourceManager.java:209)
	at com.sina.weibo.sdk.utils.ResourceManager.getNinePatchDrawable(ResourceManager.java:114)
	at com.sina.weibo.sdk.component.WeiboSdkBrowser.initTitleBar(WeiboSdkBrowser.java:377)
	at com.sina.weibo.sdk.component.WeiboSdkBrowser.setContentView(WeiboSdkBrowser.java:273)
	at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:131)
	at android.app.Activity.performCreate(Activity.java:5600)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2504)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2599)
	at android.app.ActivityThread.access$900(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5748)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by xmstudio** [comment]
最新sdk 也是出错

**Comment by lwangwangl** [comment]
最近下的sdk还是会报这个错误，请问该怎么解决

**Comment by ctjy** [comment]
手机未安装微博客户端，使用web验证时，还是会出现楼上问题。jar包版本为3.1.2 依赖的是WeiboSDK工程。
Stack trace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.newsand.duobao/com.sina.weibo.sdk.component.WeiboSdkBrowser}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2540)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2599)
at android.app.ActivityThread.access$900(ActivityThread.java:174)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5748)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.content.res.AssetManager.openAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:316)
at android.content.res.AssetManager.open(AssetManager.java:290)
at com.sina.weibo.sdk.utils.ResourceManager.getDrawableFromAssert(ResourceManager.java:209)
at com.sina.weibo.sdk.utils.ResourceManager.getNinePatchDrawable(ResourceManager.java:114)
at com.sina.weibo.sdk.component.WeiboSdkBrowser.initTitleBar(WeiboSdkBrowser.java:377)
at com.sina.weibo.sdk.component.WeiboSdkBrowser.setContentView(WeiboSdkBrowser.java:273)
at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:131)
at android.app.Activity.performCreate(Activity.java:5600)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2504)
... 11 more
java.lang.NullPointerException
at android.content.res.AssetManager.openAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:316)
at android.content.res.AssetManager.open(AssetManager.java:290)
at com.sina.weibo.sdk.utils.ResourceManager.getDrawableFromAssert(ResourceManager.java:209)
at com.sina.weibo.sdk.utils.ResourceManager.getNinePatchDrawable(ResourceManager.java:114)
at com.sina.weibo.sdk.component.WeiboSdkBrowser.initTitleBar(WeiboSdkBrowser.java:377)
at com.sina.weibo.sdk.component.WeiboSdkBrowser.setContentView(WeiboSdkBrowser.java:273)
at com.sina.weibo.sdk.component.WeiboSdkBrowser.onCreate(WeiboSdkBrowser.java:131)
at android.app.Activity.performCreate(Activity.java:5600)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2504)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2599)
at android.app.ActivityThread.access$900(ActivityThread.java:174)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5748)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)

**Comment by AngelBo** [comment]
我也是的  我现在下载最新版本的还是在合格错误  我手机没有安装微博，调用网页的视乎就会出现这个bufg
