### ISSUE TITLE
SDK4.4.3:  分享抛出 android.os.TransactionTooLargeException 异常

### ISSUE THREAD

**Issue by fanfanDaa** [sinaweibosdk/weibo_android_sdk#511]
你好，使用sdk4.4.3 , 以图片带文字+链接的形式分享， 分享方式如下， 报TransactionTooLargeException 异常。

 private void shareToWeiBo(String linkUrl, ,final Uri uri, String content) {
        WeiboMultiMessage weiboMessage = new WeiboMultiMessage();
        if(!TextUtils.isEmpty(linkUrl)){
            String  text = content == null ? linkUrl : content + linkUrl;
            if (!checkArgs(content, 1024)) {
                TextObject textObject = new TextObject();
                textObject.text = text;
                if(!checkArgs(linkUrl,512)){
                    textObject.actionUrl = linkUrl;
                }
                weiboMessage.textObject = textObject;
            }
        }

        ImageObject imageObject = new ImageObject();
        Bitmap bitmap = null;
        if (uri != null) {
            bitmap = Utils.getBitmap(this, uri);
        }
        if (bitmap != null) {
            imageObject.setImageObject(bitmap);
        }
        weiboMessage.imageObject = imageObject;

        mShareHandler.shareMessage(weiboMessage, true);

        if (bitmap != null && !bitmap.isRecycled()) {
            bitmap.recycle();
        }
    }
发生异常时，  textObject.text内容是： ”村里男女从不对外婚嫁。 https://4g.baizhan.net/55/2/44983_0.html?chann=55?jinli” 
textObject.actionUrl 内容是： “ https://4g.baizhan.net/55/2/44983_0.html?chann=55?jinli”
bitmap 物理大小是416K，宽高是2280*1080，bitmap字节数644831，并未超过sdk 中imageData 2097152的限制。
-----------------------------------------------------------------------------------------------------
2019-12-20 15:46:08.045 1160-2167/? E/ActivityTaskManager: Transaction too large, intent: Intent { cmp=com.test.share/com.sina.weibo.sdk.share.WbShareTransActivity (has extras) }, extras size: 665184, icicle size: 0
2019-12-20 15:46:08.054 1160-2167/? E/ActivityTaskManager: Second failure launching com.test.share/com.sina.weibo.sdk.share.WbShareTransActivity, giving up
    android.os.TransactionTooLargeException: data parcel size 668928 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:510)
        at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2523)
        at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:135)
        at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
        at com.android.server.wm.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:890)
        at com.android.server.wm.RootActivityContainer.attachApplication(RootActivityContainer.java:783)
        at com.android.server.wm.ActivityTaskManagerService$LocalService.attachApplication(ActivityTaskManagerService.java:6970)
        at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:5355)
        at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:5432)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2030)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2918)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

**Comment by sinaweibosdk** [comment]
imageData 太大了，系统会有限制

**Comment by sinaweibosdk** [comment]
目前分享单张图片的时候，如果图片太大会有该异常发生。
可以考虑使用分享多图，设置MultiImageObject来实现分享较大的图片。

**Comment by fanfanDaa** [comment]
目前来看，只要分享超过400K的图片，就会抛出这个异常了
好的，尝试替换成分享多图看看
