### ISSUE TITLE
 Couldn't load weibosdkcore from loader dalvik.system.PathClassLoader

### ISSUE THREAD

**Issue by BaronZ** [sinaweibosdk/weibo_android_sdk#52]
从错误收集中收到的错误，日志如下，
`java.lang.UnsatisfiedLinkError: Couldn't load weibosdkcore from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.nahuo.wp-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.xxx.xxx-2, /vendor/lib, /system/lib]]]: findLibrary returned null
    at java.lang.Runtime.loadLibrary(Runtime.java:355)
    at java.lang.System.loadLibrary(System.java:525)
    at com.sina.weibo.sdk.net.HttpManager.(HttpManager.java:83)
    at com.sina.weibo.sdk.net.AsyncWeiboRunner.request(AsyncWeiboRunner.java:84)
    at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:307)
    at com.sina.weibo.sdk.utils.AidTask.access$2(AidTask.java:294)
    at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:159)
    at java.lang.Thread.run(Thread.java:841)`

**Comment by BaronZ** [comment]
安卓版本4.4，机型未知

**Comment by RockyLin** [comment]
如果是用的Android Studio, 把sdk中的.so文件加入libs文件夹，然后在module的build.gradle文件中（不是project的builder.gradle), sourceSets下面的main中加入jniLibs.srcDirs = ['libs']。指明jniLibs的位置。

**Comment by BaronZ** [comment]
没用as，用的是eclipse，只是把weibosdkcore放入libs目录。这样操作正确不?

**Comment by RockyLin** [comment]
Eclipse看官方的demo

**Comment by oHeHeHou** [comment]
这个问题依然不不能解决。在eclipse上sdk使用正常， 换到Android studio上依然报错，以上方法都尝试过

**Comment by jasonrongdevelop** [comment]
这个是缺少对应的so库，无arm v7的是so库
