### ISSUE TITLE
小米2s-android 4.0 : java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by BaronZ** [sinaweibosdk/weibo_android_sdk#53]
手机型号：小米2s
android版本：4.0
webosdkcore版本：3.0.1

``` java
java.lang.ExceptionInInitializerError
    at com.sina.weibo.sdk.net.AsyncWeiboRunner.request(AsyncWeiboRunner.java:84)
    at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:307)
    at com.sina.weibo.sdk.utils.AidTask.access$2(AidTask.java:294)
    at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:159)
    at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load weibosdkcore: findLibrary returned null
    at java.lang.Runtime.loadLibrary(Runtime.java:365)
    at java.lang.System.loadLibrary(System.java:535)
    at com.sina.weibo.sdk.net.HttpManager.(HttpManager.java:83)
    ... 5 more
```

**Comment by 330939204** [comment]
我把so文件放到了-v7a文件夹中，而不是放在armeabi文件夹中，就可以了。。。

**Comment by tongcpp** [comment]
可以从armeabi复制一份.so到armeabi-v7a文件夹
