### ISSUE TITLE
分享多图闪退！

### ISSUE THREAD

**Issue by sinyu1012** [sinaweibosdk/weibo_android_sdk#554]
未安装 微博 客户端的情况下，并且设置了支持 web 分享，分享多图后 SDK 报错闪退。堆栈如下：

```
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.sina.weibo.sdk.c.a$a.packageName' on a null object reference
        at com.sina.weibo.sdk.share.d.a(SourceFile:1149)
        at com.sina.weibo.sdk.share.d.doInBackground(SourceFile:20)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 

```

**Comment by solochen** [comment]
这个问题一直存在，我这边更新到10.10.0，在未安装微博时分享依然报同样的错:


1 java.lang.RuntimeException:An error occurred while executing doInBackground()
--
2 android.os.AsyncTask$4.done(AsyncTask.java:399)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to read from field 'java.lang.String com.sina.weibo.sdk.c.a$a.packageName' on a null object reference
6 com.sina.weibo.sdk.share.d.a(SourceFile:4)
7 com.sina.weibo.sdk.share.d.doInBackground(SourceFile:1)
8 android.os.AsyncTask$3.call(AsyncTask.java:378)
9 java.util.concurrent.FutureTask.run(FutureTask.java:266)
10 android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
11 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
13 java.lang.Thread.run(Thread.java:919)
