### ISSUE TITLE
 library "libwind.so" not found

### ISSUE THREAD

**Issue by tudoutiao** [sinaweibosdk/weibo_android_sdk#574]
lib路径下已存放libwind.so  Android11 模拟器运行异常  <11 运行正常

implementation 'com.sina.weibo.sdk:core:4.4.3:openDefaultRelease@aar'

 java.lang.UnsatisfiedLinkError: dlopen failed: library "libwind.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.weibo.ssosdk.WeiboSsoSdk.<clinit>(WeiboSsoSdk.java:23)
        at com.weibo.ssosdk.WeiboSsoSdk.initConfig(Unknown Source:0)
        at com.sina.weibo.sdk.sso.WeiboSsoManager.init(WeiboSsoManager.java:37)
        at com.sina.weibo.sdk.WbSdk.install(WbSdk.java:33)
        at com.gozap.chouti.api.SinaApi.initSDk(SinaApi.java:108)

**Comment by wangfeng211** [comment]
我也遇到这个问题了，而且在debugger 下没问题，release 包直接报这个错误 然后闪退了，请问如何解决
