### ISSUE TITLE
java.lang.NumberFormatException: null

### ISSUE THREAD

**Issue by t894924815** [sinaweibosdk/weibo_android_sdk#587]
某种情况下会出现这个崩溃

> java.lang.NumberFormatException: null
    at java.lang.Long.parseLong(Long.java:557)
    at java.lang.Long.parseLong(Long.java:636)
    at com.sina.weibo.sdk.auth.Oauth2AccessToken.parseAccessToken(SourceFile:87)
    at com.sina.weibo.sdk.web.a.a.onPageFinished(SourceFile:1103)
    at xv0.b(chromium-TrichromeWebViewGoogle6432.aab-stable-447207734:2)
    at h9.handleMessage(chromium-TrichromeWebViewGoogle6432.aab-stable-447207734:61)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:261)
    at android.app.ActivityThread.main(ActivityThread.java:8240)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

![image](https://user-images.githubusercontent.com/12178611/122359352-0fa67080-cf88-11eb-9704-f4d4e7288c85.png)
![image](https://user-images.githubusercontent.com/12178611/122359378-1503bb00-cf88-11eb-9360-8f93244570c4.png)

**Comment by t894924815** [comment]
希望尽快修复
