### ISSUE TITLE
openDefault-11.8.1 抛 java.lang.UnsatisfiedLinkError: dlopen failed: library "libsharewind.so" not found

### ISSUE THREAD

**Issue by androidliujp** [sinaweibosdk/weibo_android_sdk#611]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libsharewind.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at com.weibo.ssosdk.WeiboSsoSdk.<clinit>(SourceFile:23)
        at com.weibo.ssosdk.WeiboSsoSdk.initConfig(Unknown Source:0)
        at com.sina.weibo.sdk.a.a(SourceFile:1072)
        at com.sina.weibo.sdk.openapi.a.registerApp(SourceFile:37)

**Comment by deppan** [comment]
把 libwind.so 重命名为 libsharewind.so

**Comment by GstXu** [comment]
> 把 libwind.so 重命名为 libsharewind.so

请问libwind.so 这个是在哪里拿的
