### ISSUE TITLE
Android Studio环境下无法加载lib

### ISSUE THREAD

**Issue by oHeHeHou** [sinaweibosdk/weibo_android_sdk#65]
操作步骤：
1.解压下载的zip，将libs文件夹下的armeabi，mips，x86文件夹拷到工程的libs文件夹下，并且在libs下创建armeabi-v7a，并放入.so文件。
2.在libs文件夹下放入weibosdkcore_v3.0.1.jar
3.在build.gradle中，android {...}下增加:
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
4.manifest中加入WeiboSdkBrowser的声明
5.代码中，调用：
            mAuthInfo = new AuthInfo(this, AuthConstants.APP_KEY, AuthConstants.REDIRECT_URL, "");
            mSsoHandler = new SsoHandler(LauncherActivity.this, mAuthInfo);
            mSsoHandler.authorizeWeb(new WbAuthListener(LauncherActivity.this));
运行代码，报错：

    java.lang.UnsatisfiedLinkError: Couldn't load weibosdkcore from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cyh.wefun-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.cyh.wefun-1, /vendor/lib, /system/lib]]]: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:358)
            at java.lang.System.loadLibrary(System.java:526)
            at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:83)
            at com.sina.weibo.sdk.net.AsyncWeiboRunner.request(AsyncWeiboRunner.java:84)
            at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:307)
            at com.sina.weibo.sdk.utils.AidTask.access$2(AidTask.java:294)
            at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:159)
            at java.lang.Thread.run(Thread.java:841)

准确的说，是在执行mSsoHandler = new SsoHandler(LauncherActivity.this, mAuthInfo);这句时候报错，以上问题在eclipse环境下完全不存在。

**Comment by oHeHeHou** [comment]
问题解决了，应该在src文件夹下建jniLibs文件夹，并且将几个so包目录放入其中。
