### ISSUE TITLE
64位手机支持

### ISSUE THREAD

**Issue by qluan** [sinaweibosdk/weibo_android_sdk#68]
java.lang.UnsatisfiedLinkError: dlopen failed: &quot;/data/app/com.douban.frodo-1/lib/arm64/libweibosdkcore.so&quot; is 32-bit instead of 64-bit
    at java.lang.Runtime.loadLibrary(Runtime.java:371)
    at java.lang.System.loadLibrary(System.java:989)
    at com.sina.weibo.sdk.net.HttpManager.&lt;clinit&gt;(HttpManager.java:83)
    at com.sina.weibo.sdk.net.AsyncWeiboRunner.request(AsyncWeiboRunner.java:84)
    at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:307)
    at com.sina.weibo.sdk.utils.AidTask.access$2(AidTask.java:294)
    at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:159)
    at java.lang.Thread.run(Thread.java:818)

**Comment by binqiangsun** [comment]
64位手机的问题：
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lukouapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lukouapp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libweibosdkcore.so"

**Comment by linsea** [comment]
我也遇到这个问题, 已经过去快一年了, 新浪的人不给个说法吗?

**Comment by xiaohuzi9527** [comment]
这个问题当时我google了很多最终解决了，但真的想不起来了 在2016年02月15日 11:21 ，Linsea写道： 我也遇到这个问题, 已经过去快一年了, 新浪的人不给个说法吗? — Reply to this email directly or view it on GitHub.

**Comment by TChengZ** [comment]
@xiaohuzi9527 请问你是怎么解决的还记得不

**Comment by linsea** [comment]
@TChengZ 好像更新SDK就行了, 我们发现引起这个问题的原因是客户的手机是X86的CPU, 需要SDK里面对应平台的so库.
