### ISSUE TITLE
android SDk 接入 sso授权客户端报错 

### ISSUE THREAD

**Issue by sunyuemmd** [sinaweibosdk/weibo_android_sdk#688]
const val minAndroidSdk = 22
    const val compileSdk = 33
    const val targetSdk = 30

    //微博登录，分享
    api ("io.github.sinaweibosdk:core:13.10.5@aar")

![Uploading 20241115100750.jpg…]()
Expecting binder but got null!
2024-11-15 10:04:04.791 18816-18936 Parcel                  com.sina.weibo                       W  Expecting binder but got null!
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:1278)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.security.DesEncrypt2.getDesCode(DesEncrypt2.java:131)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.security.DesEncrypt2.getDesString(DesEncrypt2.java:81)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.account.business.a.loadAccountsFromDB(AccountCenter.java:242)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.account.business.a.loadAccountFromDBNew(AccountCenter.java:99)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.x.c.k(Controller.java:4332)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.PushService.a(PushService.java:904)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.PushService$6.run(PushService.java:844)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.ch.h.run(PriorityRunnable.java:58)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2024-11-15 10:04:04.801 18816-18863 System.err              com.sina.weibo                       W  	at java.lang.Thread.run(Thread.java:1015)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  java.lang.NullPointerException: Attempt to get length of null array
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:46)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.security.DesEncrypt2.getDesString(DesEncrypt2.java:81)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.account.business.a.loadAccountsFromDB(AccountCenter.java:242)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.account.business.a.loadAccountFromDBNew(AccountCenter.java:99)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.x.c.k(Controller.java:4332)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.PushService.a(PushService.java:904)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.PushService$6.run(PushService.java:844)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at com.sina.weibo.ch.h.run(PriorityRunnable.java:58)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2024-11-15 10:04:04.802 18816-18863 System.err              com.sina.weibo                       W  	at java.lang.Thread.run(Thread.java:1015)

**Comment by sunyuemmd** [comment]
![20241115100750](https://github.com/user-attachments/assets/6154069e-b670-4d4a-8539-0847c1a3d1cd)

**Comment by sunyuemmd** [comment]
![DINGTALK_IM_4135467717](https://github.com/user-attachments/assets/db06a227-b002-4b23-92d6-956714306610)
