### ISSUE TITLE
部分机型Class not found when unmarshalling: com.sina.weibo.sdk.api.VideoObject

### ISSUE THREAD

**Issue by cikichen** [sinaweibosdk/weibo_android_sdk#99]
```
09-28 14:59:24.622 1638-11554/? E/Parcel: Class not found when unmarshalling: com.sina.weibo.sdk.api.VideoObject
09-28 14:59:24.622 1638-11554/? E/Parcel: java.lang.ClassNotFoundException: com.sina.weibo.sdk.api.VideoObject
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.Class.classForName(Native Method)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.Class.forName(Class.java:251)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.Class.forName(Class.java:216)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readParcelable(Parcel.java:2097)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readValue(Parcel.java:2013)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Bundle.unparcel(Bundle.java:249)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Bundle.keySet(Bundle.java:345)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.content.Intent.toUriInner(Intent.java:7131)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.content.Intent.toUri(Intent.java:7086)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.ald.o(SourceFile:38)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.ald.n(SourceFile:25)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.awf$c.a(SourceFile:253)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at com.tencent.permissionfw.permission.a.a(SourceFile:126)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at com.tencent.permissionfw.permission.a.B(SourceFile:168)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at com.tencent.permissionfw.permission.a.ad(SourceFile:262)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.awt$a.onTransact(SourceFile:114)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Binder.execTransact(Binder.java:404)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at dalvik.system.NativeStart.run(Native Method)
09-28 14:59:24.622 1638-11554/? E/Parcel:  Caused by: java.lang.NoClassDefFoundError: com/sina/weibo/sdk/api/VideoObject
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.Class.classForName(Native Method) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.Class.forName(Class.java:251) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.Class.forName(Class.java:216) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readParcelableCreator(Parcel.java:2133) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readParcelable(Parcel.java:2097) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readValue(Parcel.java:2013) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readArrayMapInternal(Parcel.java:2314) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Bundle.unparcel(Bundle.java:249) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Bundle.keySet(Bundle.java:345) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.content.Intent.toUriInner(Intent.java:7131) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.content.Intent.toUri(Intent.java:7086) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.ald.o(SourceFile:38) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.ald.n(SourceFile:25) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.awf$c.a(SourceFile:253) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at com.tencent.permissionfw.permission.a.a(SourceFile:126) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at com.tencent.permissionfw.permission.a.B(SourceFile:168) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at com.tencent.permissionfw.permission.a.ad(SourceFile:262) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.awt$a.onTransact(SourceFile:114) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Binder.execTransact(Binder.java:404) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at dalvik.system.NativeStart.run(Native Method) 
09-28 14:59:24.622 1638-11554/? E/Parcel:  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.api.VideoObject" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-28 14:59:24.622 1638-11554/? E/Parcel:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.Class.classForName(Native Method) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.Class.forName(Class.java:251) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at java.lang.Class.forName(Class.java:216) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readParcelableCreator(Parcel.java:2133) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readParcelable(Parcel.java:2097) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readValue(Parcel.java:2013) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Parcel.readArrayMapInternal(Parcel.java:2314) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Bundle.unparcel(Bundle.java:249) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Bundle.keySet(Bundle.java:345) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.content.Intent.toUriInner(Intent.java:7131) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.content.Intent.toUri(Intent.java:7086) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.ald.o(SourceFile:38) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.ald.n(SourceFile:25) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.awf$c.a(SourceFile:253) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at com.tencent.permissionfw.permission.a.a(SourceFile:126) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at com.tencent.permissionfw.permission.a.B(SourceFile:168) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at com.tencent.permissionfw.permission.a.ad(SourceFile:262) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at tcs.awt$a.onTransact(SourceFile:114) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at android.os.Binder.execTransact(Binder.java:404) 
09-28 14:59:24.622 1638-11554/? E/Parcel:     at dalvik.system.NativeStart.run(Native Method) 
09-28 14:59:24.622 1638-11554/? W/System.err: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.sina.weibo.sdk.api.VideoObject
09-28 14:59:24.622 1638-11554/? W/System.err:     at android.os.Parcel.readParcelableCreator(Parcel.java:2147)
09-28 14:59:24.622 1638-11554/? W/System.err:     at android.os.Parcel.readParcelable(Parcel.java:2097)
09-28 14:59:24.622 1638-11554/? W/System.err:     at android.os.Parcel.readValue(Parcel.java:2013)
09-28 14:59:24.622 1638-11554/? W/System.err:     at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
09-28 14:59:24.622 1638-11554/? W/System.err:     at android.os.Bundle.unparcel(Bundle.java:249)
09-28 14:59:24.622 1638-11554/? W/System.err:     at android.os.Bundle.keySet(Bundle.java:345)
09-28 14:59:24.622 1638-11554/? W/System.err:     at android.content.Intent.toUriInner(Intent.java:7131)
09-28 14:59:24.622 1638-11554/? W/System.err:     at android.content.Intent.toUri(Intent.java:7086)
09-28 14:59:24.622 1638-11554/? W/System.err:     at tcs.ald.o(SourceFile:38)
09-28 14:59:24.622 1638-11554/? W/System.err:     at tcs.ald.n(SourceFile:25)
09-28 14:59:24.622 1638-11554/? W/System.err:     at tcs.awf$c.a(SourceFile:253)
09-28 14:59:24.622 1638-11554/? W/System.err:     at com.tencent.permissionfw.permission.a.a(SourceFile:126)
09-28 14:59:24.622 1638-11554/? W/System.err:     at com.tencent.permissionfw.permission.a.B(SourceFile:168)
09-28 14:59:24.622 1638-11554/? W/System.err:     at com.tencent.permissionfw.permission.a.ad(SourceFile:262)
09-28 14:59:24.622 1638-11554/? W/System.err:     at tcs.awt$a.onTransact(SourceFile:114)
09-28 14:59:24.622 1638-11554/? W/System.err:     at android.os.Binder.execTransact(Binder.java:404)
09-28 14:59:24.622 1638-11554/? W/System.err:     at dalvik.system.NativeStart.run(Native Method)
```

唉，微信，qq，微博，这三个SDK，我真的对新浪的SDK有种恐惧感了，如果不是产品需求，我真心不想要加新浪的分享了。能对开发者造成心理阴影的SDK也只有微博了吧

**Comment by Freerain9** [comment]
请问最后是怎么解决的？？
